(function () {
  if (window.GRAPH_NODES) return;

  window.GRAPH_MODULES = {
    algo:    { label: '算法',       color: '#38bdf8' },
    db:      { label: '数据库',     color: '#fbbf24' },
    redis:   { label: 'Redis',      color: '#dc382c' },
    linux:   { label: 'Linux',      color: '#6ee7b7' },
    network: { label: '网络',        color: '#10b981' },
    kafka:   { label: 'Kafka',      color: '#ff6b35' },
    cs:      { label: '组成原理',   color: '#a78bfa' },
    golang:  { label: 'Golang',     color: '#00add8' },
    distributed: { label: '分布式',     color: '#c084fc' },
    ai:      { label: 'AI 系统',     color: '#8b5cf6' },
    'system-design': { label: '系统设计', color: '#f59e0b' }
  };

  window.GRAPH_NODES = [
    {id:'algo', label:'数据结构与算法', module:'algo', type:'module', href:'algo/index.html', desc:'排序、树、图、动态规划与工程常用数据结构。'},
    {id:'db', label:'数据库原理', module:'db', type:'module', href:'db/index.html', desc:'从 SQL 解析到索引、事务、日志、缓存和分布式数据库。'},
    {id:'redis', label:'Redis 原理', module:'redis', type:'module', href:'redis/index.html', desc:'内存数据结构、持久化、淘汰策略、集群和分布式锁。'},
    {id:'linux', label:'Linux', module:'linux', type:'module', href:'linux/index.html', desc:'命令、进程、内存、I/O、文件系统和调度器。'},
    {id:'network', label:'计算机网络', module:'network', type:'module', href:'network/index.html', desc:'TCP/IP、HTTP、DNS、TLS、负载均衡和现代 QUIC。'},
    {id:'kafka', label:'Kafka', module:'kafka', type:'module', href:'kafka/index.html', desc:'Producer、Consumer、分区副本、消费者组和现代 KRaft 方向。'},
    {id:'cs', label:'计算机组成原理', module:'cs', type:'module', href:'cs/index.html', desc:'CPU、指令、流水线、缓存层次、内存寻址和 I/O 总线。'},
    {id:'golang', label:'Golang', module:'golang', type:'module', href:'golang/index.html', desc:'35 个专题：GMP 调度、GC、Channel、逃逸分析、内存模型、并发模式和工程实践。'},
    {id:'distributed', label:'分布式系统', module:'distributed', type:'module', href:'distributed/index.html', desc:'CAP、Raft、Paxos、一致性哈希等分布式系统基础概念。'},
    {id:'ai', label:'AI 系统', module:'ai', type:'module', href:'ai/index.html', desc:'从 LLM 原理、推理、RAG、Agent 到训练、MoE、评测和部署的工程化知识。'},
    {id:'system-design', label:'系统设计', module:'system-design', type:'module', href:'system-design/index.html', desc:'短链、限流、分布式 ID、消息推送、秒杀——把算法和中间件组装成真实系统。'},
    {id:'sd-short-url', label:'短链系统', module:'system-design', type:'page', href:'system-design/short-url.html', desc:'URL 哈希、Base62 编码、数据库持久化、Redis 缓存和 302 重定向的完整链路。'},
    {id:'sd-rate-limiter', label:'限流器', module:'system-design', type:'page', href:'system-design/rate-limiter.html', desc:'令牌桶、滑动窗口、分布式限流（Redis Lua）和多级降级策略。'},
    {id:'sd-distributed-id', label:'分布式 ID', module:'system-design', type:'page', href:'system-design/distributed-id.html', desc:'Snowflake 位布局、时钟回拨处理、Leaf 号段模式和多机分配。'},
    {id:'sd-push-system', label:'消息推送系统', module:'system-design', type:'page', href:'system-design/push-system.html', desc:'长连接管理、Kafka 消息分发、扇出写/扇出读、ACK 和重试机制。'},
    {id:'sd-flash-sale', label:'秒杀系统', module:'system-design', type:'page', href:'system-design/flash-sale.html', desc:'流量漏斗、Redis 预扣库存、Kafka 异步下单、降级兜底和数据一致性。'},
    {id:'ai-llm-overview', label:'LLM 基础概念', module:'ai', type:'page', href:'ai/llm-overview.html', desc:'解释 Token、Embedding、预训练、微调、对齐和上下文窗口，是理解 LLM 系统的入口。'},
    {id:'ai-attention', label:'Transformer Attention', module:'ai', type:'page', href:'ai/transformer-attention.html', desc:'用 Q/K/V、Mask、Softmax 和 Multi-Head 动画理解 Transformer 如何聚合上下文。'},
    {id:'ai-kv-cache', label:'推理与 KV Cache', module:'ai', type:'page', href:'ai/inference-kv-cache.html', desc:'展示 Tokenize、Prefill、Decode、Sampling 和 Streaming 的在线推理链路。'},
    {id:'ai-rag', label:'RAG Pipeline', module:'ai', type:'page', href:'ai/rag-pipeline.html', desc:'串起 Chunk、Embedding、向量索引、召回、重排、Prompt 组装和生成。'},
    {id:'ai-agent', label:'Agent Tool Calling', module:'ai', type:'page', href:'ai/agent-tool-calling.html', desc:'解释 Planner、工具调用、Observation、Memory、Guardrail 和停止条件组成的 Agent 循环。'},
    {id:'ai-training', label:'Training Pipeline', module:'ai', type:'page', href:'ai/training-pipeline.html', desc:'展示 Dataset、Tokenize、Batch、Forward、Loss、Backward、Optimizer 和 Checkpoint 的训练主链路。'},
    {id:'ai-moe', label:'Mixture of Experts', module:'ai', type:'page', href:'ai/mixture-of-experts.html', desc:'用 Router、Top-k Expert、容量限制和负载均衡理解 MoE 稀疏激活架构。'},
    {id:'ai-eval-deploy', label:'AI 评测与部署', module:'ai', type:'page', href:'ai/eval-deploy.html', desc:'讲 Golden Set、灰度、观测、成本、延迟、Prompt 版本和回滚组成的上线闭环。'},
    {id:'algo-bubble-sort', label:'冒泡排序', module:'algo', type:'page', href:'algo/bubble-sort.html', desc:'相邻元素比较交换，适合理解排序稳定性和局部有序。'},
    {id:'algo-selection-sort', label:'选择排序', module:'algo', type:'page', href:'algo/selection-sort.html', desc:'每轮选择最小元素放到有序区，展示选择型排序思想。'},
    {id:'algo-insertion-sort', label:'插入排序', module:'algo', type:'page', href:'algo/insertion-sort.html', desc:'维护有序前缀，将新元素插入正确位置。'},
    {id:'algo-merge-sort', label:'归并排序', module:'algo', type:'page', href:'algo/merge-sort.html', desc:'分治拆分再归并有序序列，稳定且复杂度 O(n log n)。'},
    {id:'algo-quick-sort', label:'快速排序', module:'algo', type:'page', href:'algo/quick-sort.html', desc:'基于 pivot 分区的原地排序，是工程中常见的排序基础。'},
    {id:'algo-heap-sort', label:'堆排序', module:'algo', type:'page', href:'algo/heap-sort.html', desc:'利用堆结构反复取最大或最小元素完成排序。'},
    {id:'algo-counting-sort', label:'计数排序', module:'algo', type:'page', href:'algo/counting-sort.html', desc:'用计数数组处理有限整数范围内的线性排序。'},
    {id:'algo-radix-sort', label:'基数排序', module:'algo', type:'page', href:'algo/radix-sort.html', desc:'按位分桶排序，适合固定长度整数或字符串。'},
    {id:'topo', label:'拓扑排序', module:'algo', type:'page', href:'algo/topological-sort.html', desc:'处理 DAG 依赖顺序，常见于任务调度、数据管道和构建依赖。'},
    {id:'binary-search', label:'二分查找', module:'algo', type:'page', href:'algo/binary-search.html', desc:'在有序空间中快速定位边界，是索引查找、范围查询和分片定位的基础。'},
    {id:'kmp', label:'KMP / 字符串匹配', module:'algo', type:'page', href:'algo/kmp.html', desc:'高效字符串匹配思想，可连接日志检索、协议解析和关键字过滤。'},
    {id:'algo-linked-list', label:'链表', module:'algo', type:'page', href:'algo/linked-list.html', desc:'通过指针连接节点，适合理解插入删除和内存局部性取舍。'},
    {id:'algo-stack', label:'栈', module:'algo', type:'page', href:'algo/stack.html', desc:'后进先出结构，连接递归、表达式解析和调用栈。'},
    {id:'algo-queue', label:'队列', module:'algo', type:'page', href:'algo/queue.html', desc:'先进先出结构，连接 BFS、任务调度和消息缓冲。'},
    {id:'heap', label:'堆 / Top-K', module:'algo', type:'page', href:'algo/heap.html', desc:'优先队列、外部排序、调度和 Top-K 的底层结构。'},
    {id:'hash', label:'哈希表 / 哈希索引', module:'algo', type:'page', href:'algo/hash-table.html', desc:'O(1) 平均查找的基础，也是缓存、索引和分片的关键。'},
    {id:'skiplist', label:'跳表', module:'algo', type:'page', href:'algo/skip-list.html', desc:'多层链表的概率平衡结构，Redis 大 ZSet 常见基础。'},
    {id:'algo-bst', label:'二叉搜索树', module:'algo', type:'page', href:'algo/binary-search-tree.html', desc:'通过左右子树有序性支持查找、插入和删除。'},
    {id:'algo-avl', label:'AVL 树', module:'algo', type:'page', href:'algo/avl-tree.html', desc:'严格平衡的二叉搜索树，用旋转控制高度。'},
    {id:'algo-btree', label:'B 树', module:'algo', type:'page', href:'algo/b-tree.html', desc:'多路平衡搜索树，是理解磁盘友好索引的前置结构。'},
    {id:'algo-bplus', label:'算法 B+ 树', module:'algo', type:'page', href:'algo/b-plus-tree.html', desc:'从数据结构角度理解 B+ 树节点、分裂与范围遍历。'},
    {id:'trie', label:'Trie 前缀树', module:'algo', type:'page', href:'algo/trie.html', desc:'前缀匹配结构，可用于 DNS 域名层级、路由匹配、自动补全和字典检索。'},
    {id:'segment-tree', label:'线段树 / 区间聚合', module:'algo', type:'page', href:'algo/segment-tree.html', desc:'维护区间聚合和在线更新，可类比监控窗口、时间序列和区间统计。'},
    {id:'algo-tree-traversal', label:'树遍历', module:'algo', type:'page', href:'algo/tree-traversal.html', desc:'前序、中序、后序和层序遍历帮助理解树结构访问顺序。'},
    {id:'union-find', label:'并查集', module:'algo', type:'page', href:'algo/union-find.html', desc:'高效维护连通分量，可类比集群成员、网络分区和副本组连通性。'},
    {id:'bfs', label:'BFS', module:'algo', type:'page', href:'algo/bfs.html', desc:'逐层扩展的图遍历算法，用于最短跳数、依赖扩散和网络连通性分析。'},
    {id:'dfs', label:'DFS', module:'algo', type:'page', href:'algo/dfs.html', desc:'深度优先遍历可用于环检测、死锁检测、拓扑排序和依赖图分析。'},
    {id:'dijkstra', label:'Dijkstra', module:'algo', type:'page', href:'algo/dijkstra.html', desc:'单源最短路径算法，是理解路由选择、网络代价和服务路径优化的基础。'},
    {id:'algo-bellman-ford', label:'Bellman-Ford', module:'algo', type:'page', href:'algo/bellman-ford.html', desc:'可处理负权边的单源最短路径算法。'},
    {id:'algo-kruskal', label:'Kruskal', module:'algo', type:'page', href:'algo/kruskal.html', desc:'基于并查集构造最小生成树。'},
    {id:'algo-knapsack', label:'背包问题', module:'algo', type:'page', href:'algo/knapsack.html', desc:'动态规划经典问题，展示状态与选择的关系。'},
    {id:'algo-lcs', label:'最长公共子序列', module:'algo', type:'page', href:'algo/lcs.html', desc:'用二维动态规划处理序列匹配。'},
    {id:'algo-lis', label:'最长递增子序列', module:'algo', type:'page', href:'algo/lis.html', desc:'连接动态规划、二分优化和有序边界维护。'},
    {id:'db-architecture', label:'数据库架构', module:'db', type:'page', href:'db/db-architecture.html', desc:'从连接层、解析优化、执行引擎到存储引擎理解数据库整体链路。'},
    {id:'query-path', label:'查询执行路径', module:'db', type:'page', href:'db/query-path.html', desc:'SQL 从客户端到磁盘页的完整执行路径。'},
    {id:'storage-layout', label:'存储布局 / 页', module:'db', type:'page', href:'db/storage-layout.html', desc:'页、区、段和磁盘布局，是 B+ 树、Buffer Pool、WAL 的物理基础。'},
    {id:'buffer', label:'Buffer Pool', module:'db', type:'page', href:'db/buffer-pool.html', desc:'数据库页缓存，和 LRU、脏页、WAL 强相关。'},
    {id:'wal', label:'WAL / Redo', module:'db', type:'page', href:'db/wal.html', desc:'先写日志再写数据页，保证崩溃恢复。'},
    {id:'mysql-logs', label:'MySQL 日志体系', module:'db', type:'page', href:'db/mysql-logs.html', desc:'Redo Log / Binlog 分工、checkpoint 机制和 CDC 数据同步链路。'},
    {id:'bplus', label:'B+ 树', module:'db', type:'page', href:'db/btree-index.html', desc:'数据库主流索引结构，依赖多路平衡树、页和叶子链表。'},
    {id:'db-hash-index', label:'哈希索引', module:'db', type:'page', href:'db/hash-index.html', desc:'通过 hash 映射定位记录，适合等值查询但不适合范围扫描。'},
    {id:'db-query-plan', label:'查询计划', module:'db', type:'page', href:'db/query-plan.html', desc:'优化器选择访问路径、Join 顺序和执行算子的成本模型。'},
    {id:'join', label:'Join 算法', module:'db', type:'page', href:'db/join-algo.html', desc:'Nested Loop、Hash Join、Sort-Merge Join 的执行代价。'},
    {id:'sort', label:'外部排序', module:'db', type:'page', href:'db/external-sort.html', desc:'分块排序与 K 路归并，依赖堆和磁盘 I/O。'},
    {id:'mvcc', label:'MVCC', module:'db', type:'page', href:'db/mvcc.html', desc:'通过版本链和快照读实现读写不阻塞。'},
    {id:'locks', label:'锁 / 死锁', module:'db', type:'page', href:'db/transaction.html', desc:'两阶段锁、等待图和 DFS 环检测。'},
    {id:'distributed-db', label:'分布式数据库', module:'db', type:'page', href:'db/distributed-db.html', desc:'CAP、Raft、分片和副本，和 Kafka ISR、网络分区、一致性语义相互关联。'},
    {id:'cache-layers', label:'缓存分层', module:'db', type:'page', href:'db/cache-layers.html', desc:'从浏览器、CDN、应用缓存、Redis 到数据库 Buffer Pool 的多级缓存链路。'},
    {id:'redis-types', label:'Redis 数据类型', module:'redis', type:'page', href:'redis/data-types.html', desc:'String/List/Hash/Set/ZSet 与 listpack、quicklist、skiplist。'},
    {id:'redis-persistence', label:'Redis 持久化', module:'redis', type:'page', href:'redis/persistence.html', desc:'RDB、AOF、rewrite 与 fsync 策略，和 WAL、Page Cache、顺序写相关。'},
    {id:'redis-eviction', label:'Redis 淘汰策略', module:'redis', type:'page', href:'redis/eviction.html', desc:'LRU、LFU、TTL 与内存上限控制。'},
    {id:'redis-cluster', label:'Redis Cluster', module:'redis', type:'page', href:'redis/cluster.html', desc:'槽位分片、主从复制和故障转移，和一致性、网络分区、客户端路由相关。'},
    {id:'redis-lock', label:'Redis 分布式锁', module:'redis', type:'page', href:'redis/distributed-lock.html', desc:'SET NX PX、Lua 原子释放、Redlock 与一致性边界。'},
    {id:'epoll', label:'epoll / I/O 多路复用', module:'linux', type:'page', href:'linux/io-models.html', desc:'高并发服务器和 Redis 单线程事件循环的系统基础。'},
    {id:'vm', label:'虚拟内存 / mmap', module:'linux', type:'page', href:'linux/virtual-memory.html', desc:'页表、TLB、缺页异常、mmap 与数据库页缓存有关。'},
    {id:'fs', label:'VFS / inode', module:'linux', type:'page', href:'linux/filesystem.html', desc:'文件系统抽象，和 WAL、日志文件、零拷贝链路相关。'},
    {id:'sched', label:'CFS / EEVDF', module:'linux', type:'page', href:'linux/scheduling.html', desc:'进程调度、公平性和延迟优化。'},
    {id:'linux-commands', label:'Linux 常用命令', module:'linux', type:'page', href:'linux/commands.html', desc:'ps、ss、df、du、curl、grep 等命令连接进程、网络、磁盘和日志排障。'},
    {id:'linux-process', label:'进程生命周期', module:'linux', type:'page', href:'linux/process-lifecycle.html', desc:'进程创建、运行、阻塞、退出和回收的生命周期。'},
    {id:'tcp', label:'TCP 握手', module:'network', type:'page', href:'network/tcp-handshake.html', desc:'连接建立、关闭、TIME_WAIT 和可靠传输基础。'},
    {id:'congestion', label:'拥塞控制', module:'network', type:'page', href:'network/tcp-congestion.html', desc:'慢启动、拥塞避免、CUBIC、BBR 与网络吞吐。'},
    {id:'http', label:'HTTP/2 / HTTP/3', module:'network', type:'page', href:'network/http.html', desc:'HTTP 演进、TLS 1.3、QUIC 和队头阻塞。'},
    {id:'dns', label:'DNS / CDN', module:'network', type:'page', href:'network/dns.html', desc:'域名解析、缓存、TTL 和边缘调度。'},
    {id:'lb', label:'负载均衡', module:'network', type:'page', href:'network/load-balancing.html', desc:'四层/七层负载均衡、健康检查、会话保持和反向代理。'},
    {id:'kafka-overview', label:'Kafka 存储模型', module:'kafka', type:'page', href:'kafka/kafka-overview.html', desc:'Topic、Partition、Segment、Offset、顺序写和 Page Cache 构成 Kafka 高吞吐基础。'},
    {id:'kafka-producer', label:'Kafka Producer', module:'kafka', type:'page', href:'kafka/producer.html', desc:'Batch、linger.ms、acks、幂等性和吞吐延迟权衡。'},
    {id:'kafka-consumer', label:'Kafka Consumer', module:'kafka', type:'page', href:'kafka/consumer.html', desc:'Offset、提交语义、消费组和 Exactly Once 边界。'},
    {id:'kafka-replica', label:'Partition / ISR', module:'kafka', type:'page', href:'kafka/partition-replication.html', desc:'分区、副本、ISR、Leader 选举与高可用。'},
    {id:'kafka-group', label:'Consumer Group', module:'kafka', type:'page', href:'kafka/consumer-group.html', desc:'Rebalance、分区分配和消费扩展。'},
    {id:'cpu-pipeline', label:'CPU 指令 / 流水线', module:'cs', type:'page', href:'cs/cpu.html', desc:'取指、译码、执行、流水线、分支预测和乱序执行。'},
    {id:'cache-hierarchy', label:'Cache 层次 / 缓存行', module:'cs', type:'page', href:'cs/cache.html', desc:'L1/L2/L3、缓存行、局部性和 false sharing 的硬件基础。'},
    {id:'memory-addressing', label:'内存寻址 / TLB', module:'cs', type:'page', href:'cs/memory.html', desc:'虚拟地址、页表、MMU、TLB 和物理内存访问链路。'},
    {id:'io-bus', label:'总线 / 中断 / DMA', module:'cs', type:'page', href:'cs/io.html', desc:'设备和 CPU 之间通过总线、中断、DMA 进行高效协作。'},
    {id:'number-repr', label:'补码 / IEEE 754', module:'cs', type:'page', href:'cs/number.html', desc:'整数补码表示和 IEEE 754 浮点数格式，理解溢出和精度陷阱的底层原因。'},
    {id:'cs-barrier', label:'内存屏障', module:'cs', type:'page', href:'cs/barrier.html', desc:'Store/Load barrier、mfence、Go 内存模型的硬件根源。'},
    {id:'cs-atomic', label:'原子指令', module:'cs', type:'page', href:'cs/atomic.html', desc:'CAS、LL/SC、x86 LOCK 前缀，sync/atomic 底层实现。'},
    {id:'go-syntax', label:'Go 类型系统', module:'golang', type:'page', href:'golang/type-system.html', desc:'类型、方法集、接口、泛型和显式错误处理。'},
    {id:'go-string', label:'字符串', module:'golang', type:'page', href:'golang/string.html', desc:'字符串不可变、UTF-8、rune 和底层字节序列。'},
    {id:'go-interface', label:'Interface', module:'golang', type:'page', href:'golang/interface.html', desc:'隐式满足、nil interface 陷阱、iface/eface 内部结构。'},
    {id:'go-embedding', label:'嵌入组合', module:'golang', type:'page', href:'golang/embedding.html', desc:'通过嵌入实现组合式代码复用和方法提升。'},
    {id:'go-error', label:'Error 处理', module:'golang', type:'page', href:'golang/error.html', desc:'error 接口、sentinel、%w 包装、Is/As 展开链和自定义错误类型。'},
    {id:'go-generics', label:'泛型', module:'golang', type:'page', href:'golang/generics.html', desc:'type param、约束、any/comparable 和泛型适用场景。'},
    {id:'go-closure', label:'闭包', module:'golang', type:'page', href:'golang/closure.html', desc:'闭包捕获变量、生命周期和逃逸分析关系。'},
    {id:'go-defer-panic', label:'defer / panic / recover', module:'golang', type:'page', href:'golang/defer-panic.html', desc:'defer 执行顺序、panic 传播和 recover 边界。'},
    {id:'go-slice-map', label:'切片与 Map', module:'golang', type:'page', href:'golang/slice-map.html', desc:'slice header、扩容、map bucket 和并发安全边界。'},
    {id:'go-reflect', label:'反射', module:'golang', type:'page', href:'golang/reflect.html', desc:'Type/Value、运行时元信息和动态调用成本。'},
    {id:'go-runtime', label:'GMP 调度器', module:'golang', type:'page', href:'golang/gmp.html', desc:'G、M、P、work stealing、syscall 阻塞和 netpoller。'},
    {id:'go-gc', label:'Go GC', module:'golang', type:'page', href:'golang/gc.html', desc:'并发三色标记、写屏障、堆分配和 pprof 诊断。'},
    {id:'go-channel', label:'Channel', module:'golang', type:'page', href:'golang/channel.html', desc:'无缓冲/有缓冲 channel、close 语义、select 多路复用和 goroutine 协作模式。'},
    {id:'go-concurrency', label:'Goroutine', module:'golang', type:'page', href:'golang/goroutine.html', desc:'goroutine、channel、context 和 sync 包组成 Go 并发模型。'},
    {id:'go-mem-alloc', label:'内存分配器', module:'golang', type:'page', href:'golang/memory-alloc.html', desc:'mcache → mcentral → mheap 三级分配链路与大对象路径。'},
    {id:'go-escape', label:'逃逸分析', module:'golang', type:'page', href:'golang/escape.html', desc:'编译期决定变量在栈还是堆分配，栈分配零 GC 压力。'},
    {id:'go-select', label:'Select', module:'golang', type:'page', href:'golang/select.html', desc:'多路 channel 等待、default 非阻塞、time.After 超时模式。'},
    {id:'go-context', label:'Context', module:'golang', type:'page', href:'golang/context.html', desc:'WithCancel/WithTimeout/WithValue 取消树，控制 goroutine 生命周期。'},
    {id:'go-timer', label:'Timer/Ticker', module:'golang', type:'page', href:'golang/timer.html', desc:'time.Timer 与 Ticker 机制、Reset 竞态、goroutine 泄漏陷阱。'},
    {id:'go-patterns', label:'并发模式', module:'golang', type:'page', href:'golang/concurrent-patterns.html', desc:'pipeline、fan-out/fan-in、worker pool 的 channel 组合模式。'},
    {id:'go-memory', label:'Go 内存模型 / 同步', module:'golang', type:'page', href:'golang/memory-model.html', desc:'happens-before、Mutex、channel、atomic、data race 和 false sharing。'},
    {id:'go-sync', label:'Sync 原语', module:'golang', type:'page', href:'golang/sync.html', desc:'Mutex/RWMutex/WaitGroup/Once/Cond 使用模式与死锁场景。'},
    {id:'go-atomic', label:'Atomic', module:'golang', type:'page', href:'golang/atomic.html', desc:'原子操作、CAS、内存序和与 Mutex 的边界选择。'},
    {id:'go-syncpool', label:'sync.Pool', module:'golang', type:'page', href:'golang/syncpool.html', desc:'对象复用池、GC 回收时机和减少 GC 压力的使用场景。'},
    {id:'go-errgroup', label:'errgroup', module:'golang', type:'page', href:'golang/errgroup.html', desc:'结构化并发、goroutine 错误收集与 WaitGroup 的关系。'},
    {id:'go-stdlib', label:'io.Reader / io.Writer', module:'golang', type:'page', href:'golang/io.html', desc:'package 边界、context、io.Reader/Writer、error wrapping 和标准库资源生命周期。'},
    {id:'go-web', label:'Go Web / RPC 服务', module:'golang', type:'page', href:'golang/http.html', desc:'net/http、middleware、handler/service/repo 分层、超时、连接池和优雅退出。'},
    {id:'go-json', label:'encoding/json', module:'golang', type:'page', href:'golang/json.html', desc:'JSON 编解码、标签、零值和性能优化。'},
    {id:'go-sql', label:'database/sql', module:'golang', type:'page', href:'golang/sql.html', desc:'连接池、事务、预处理和上下文取消。'},
    {id:'go-strings-bytes', label:'strings / bytes', module:'golang', type:'page', href:'golang/strings-bytes.html', desc:'字符串、字节切片和转换成本。'},
    {id:'go-modules', label:'Go Modules', module:'golang', type:'page', href:'golang/modules.html', desc:'模块版本、依赖解析和可复现构建。'},
    {id:'go-testing', label:'Go 测试', module:'golang', type:'page', href:'golang/testing.html', desc:'table-driven test、benchmark、race detector 和 pprof 组成质量闭环。'},
    {id:'go-pprof', label:'pprof 性能分析', module:'golang', type:'page', href:'golang/pprof.html', desc:'CPU、内存、阻塞和 goroutine profile 定位性能瓶颈。'},
    {id:'go-architecture', label:'Go 服务架构', module:'golang', type:'page', href:'golang/patterns.html', desc:'cmd/main、handler、service、repo、infra、配置和可观测性的工程边界。'},
    {id:'go-unsafe', label:'unsafe', module:'golang', type:'page', href:'golang/unsafe.html', desc:'unsafe.Pointer 用法、uintptr 与 GC 的关系和底层内存操作。'},
    {id:'sliding-window', label:'滑动窗口', module:'algo', type:'page', href:'algo/sliding-window.html', desc:'连续窗口内增量维护状态，是限流、TCP 拥塞窗口、流式统计的基础模式。'},
    {id:'monotonic', label:'单调队列 / 栈', module:'algo', type:'page', href:'algo/monotonic.html', desc:'维护候选集合单调性，用于窗口最值、监控峰值和实时指标计算。'},
    {id:'probabilistic-ds', label:'近似数据结构', module:'algo', type:'page', href:'algo/probabilistic-ds.html', desc:'Bloom、HLL、Count-Min Sketch 用可控误差换内存，适合海量判重、基数和频率估计。'},
    {id:'heavy-hitters', label:'Top-K / Heavy Hitters', module:'algo', type:'page', href:'algo/heavy-hitters.html', desc:'用堆、哈希和近似计数发现热点数据，连接热 key、日志分析、告警和推荐。'},
    {id:'consistent-hash', label:'一致性哈希', module:'distributed', type:'page', href:'distributed/consistent-hash.html', desc:'把 key 映射到环上，减少扩缩容时的数据迁移，是缓存、分片、负载均衡的经典算法。'},
    {id:'lru-lfu', label:'LRU / LFU', module:'redis', type:'page', href:'redis/lru-lfu.html', desc:'缓存淘汰算法，连接 Redis 淘汰策略、数据库 Buffer Pool 和多级缓存设计。'},
    {id:'bloom', label:'Bloom Filter', module:'algo', type:'page', href:'algo/bloom.html', desc:'概率型判重结构，适合缓存穿透防护与大规模集合过滤。'},
    {id:'lsm', label:'LSM Tree', module:'db', type:'page', href:'db/lsm.html', desc:'面向写入优化的存储结构，RocksDB/TiKV/LevelDB 生态常见。'},
    {id:'vector', label:'向量索引', module:'db', type:'page', href:'db/vector.html', desc:'HNSW、IVF、PQ 等 ANN 索引是 RAG 与向量数据库基础。'},
    {id:'sequential-io', label:'顺序写 / Page Cache', module:'linux', type:'page', href:'linux/sequential-io.html', desc:'Kafka、WAL、LSM 都依赖顺序写、批量刷盘和 Linux Page Cache 提升吞吐。'},
    {id:'paxos', label:'Paxos', module:'distributed', type:'page', href:'distributed/paxos.html', desc:'Multi-Paxos 是分布式一致性的理论原型，Raft 是其工程简化版。'},
    {id:'raft', label:'Raft', module:'distributed', type:'page', href:'distributed/raft.html', desc:'Leader 选举、日志复制和成员变更，是 etcd、TiKV 和 KRaft 的分布式一致性基础。'},
    {id:'cap-theorem', label:'CAP 定理', module:'distributed', type:'page', href:'distributed/cap-theorem.html', desc:'分布式系统在一致性、可用性、分区容忍性三者间的权衡。'},
    {id:'zero-copy', label:'零拷贝', module:'linux', type:'page', href:'linux/zero-copy.html', desc:'sendfile / mmap 减少内核态与用户态数据拷贝，是 Kafka 高吞吐和 HTTP 文件服务的核心优化。'},
    {id:'ebpf', label:'eBPF', module:'linux', type:'page', href:'linux/ebpf.html', desc:'现代 Linux 可观测、网络和安全能力的核心技术。'},
    {id:'cgroup', label:'cgroup / Namespace', module:'linux', type:'page', href:'linux/cgroup.html', desc:'容器资源限制和隔离的系统基础。'},
    {id:'quic', label:'QUIC', module:'network', type:'page', href:'network/quic.html', desc:'UDP 上的现代传输协议，内置 TLS 1.3、连接迁移和独立流。'},
    {id:'kraft', label:'KRaft', module:'kafka', type:'page', href:'kafka/kraft.html', desc:'Kafka 元数据管理的新模式，逐步替代 ZooKeeper。'},
    {id:'exactly-once', label:'Exactly Once', module:'kafka', type:'page', href:'kafka/exactly-once.html', desc:'幂等 Producer、事务和 offset 原子提交组合出的端到端处理语义。'},
    {id:'redis-stream', label:'Redis Stream', module:'redis', type:'page', href:'modern-topic.html?id=redis-stream', desc:'带消费者组和 ACK 的消息流结构，可与 Kafka 对比。'}
  ];

  window.GRAPH_EDGES = [
    ['cs-barrier','go-memory'],['cs-atomic','go-atomic'],['cache-hierarchy','cs-barrier'],['bplus','algo-bplus'],['bplus','buffer'],['bplus','vm'],
    ['bplus','storage-layout'],['bplus','binary-search'],['binary-search','storage-layout'],['binary-search','redis-types'],['hash','redis-types'],['hash','join'],
    ['hash','redis-eviction'],['hash','redis-cluster'],['hash','kafka-producer'],['hash','consistent-hash'],['hash','bloom'],['hash','db-hash-index'],
    ['skiplist','redis-types'],['skiplist','binary-search'],['heap','sort'],['heap','sched'],['heap','heavy-hitters'],['heap','algo-heap-sort'],
    ['bfs','dfs'],['bfs','dijkstra'],['dfs','locks'],['dfs','topo'],['dijkstra','lb'],['union-find','distributed-db'],
    ['union-find','redis-cluster'],['union-find','kafka-replica'],['topo','kafka-overview'],['topo','distributed-db'],['trie','dns'],['trie','http'],
    ['trie','lb'],['trie','kmp'],['kmp','linux-commands'],['sliding-window','congestion'],['sliding-window','tcp'],['sliding-window','http'],
    ['sliding-window','lb'],['sliding-window','heavy-hitters'],['sliding-window','kafka-consumer'],['monotonic','sliding-window'],['monotonic','segment-tree'],['monotonic','heavy-hitters'],
    ['probabilistic-ds','bloom'],['probabilistic-ds','redis-stream'],['probabilistic-ds','vector'],['probabilistic-ds','heavy-hitters'],['heavy-hitters','cache-layers'],['heavy-hitters','kafka-consumer'],
    ['consistent-hash','distributed-db'],['consistent-hash','lb'],['consistent-hash','cache-layers'],['consistent-hash','kafka-group'],['lru-lfu','redis-eviction'],['lru-lfu','buffer'],
    ['lru-lfu','cache-layers'],['bloom','cache-layers'],['bloom','vector'],['db-architecture','query-path'],['query-path','db-query-plan'],['query-path','buffer'],
    ['query-path','wal'],['query-path','mvcc'],['db-query-plan','join'],['db-query-plan','sort'],['buffer','wal'],['buffer','vm'],
    ['buffer','redis-eviction'],['buffer','cache-layers'],['wal','fs'],['wal','mvcc'],['wal','sequential-io'],['mvcc','locks'],
    ['mvcc','distributed-db'],['sort','sequential-io'],['storage-layout','fs'],['storage-layout','vm'],['cache-layers','redis-eviction'],['cache-layers','dns'],
    ['distributed-db','locks'],['distributed-db','kafka-replica'],['distributed-db','redis-cluster'],['lsm','wal'],['lsm','sequential-io'],['lsm','distributed-db'],
    ['redis-types','redis-stream'],['redis-persistence','wal'],['redis-persistence','fs'],['redis-persistence','sequential-io'],['redis-lock','locks'],['epoll','redis-types'],
    ['epoll','http'],['epoll','tcp'],['epoll','kafka-consumer'],['linux-commands','epoll'],['linux-commands','tcp'],['linux-commands','fs'],
    ['linux-commands','redis-persistence'],['linux-commands','kafka-overview'],['linux-process','sched'],['fs','kafka-overview'],['fs','sequential-io'],['vm','kafka-overview'],
    ['vm','sequential-io'],['ebpf','tcp'],['ebpf','kafka-consumer'],['cgroup','sched'],['cgroup','kafka-consumer'],['tcp','http'],
    ['tcp','kafka-producer'],['tcp','kafka-consumer'],['tcp','kafka-replica'],['congestion','http'],['congestion','kafka-producer'],['quic','http'],
    ['dns','http'],['dns','lb'],['lb','http'],['lb','kafka-consumer'],['kafka-overview','kafka-producer'],['kafka-overview','kafka-consumer'],
    ['kafka-overview','kafka-replica'],['kafka-overview','sequential-io'],['kafka-overview','wal'],['kafka-overview','lsm'],['kafka-producer','kafka-replica'],['kafka-producer','exactly-once'],
    ['kafka-consumer','kafka-group'],['kafka-consumer','exactly-once'],['kafka-group','redis-stream'],['kafka-replica','kraft'],['kraft','raft'],
    ['cpu-pipeline','sched'],['cpu-pipeline','go-runtime'],['cpu-pipeline','go-gc'],['cache-hierarchy','buffer'],['cache-hierarchy','redis-types'],['cache-hierarchy','lru-lfu'],
    ['cache-hierarchy','go-gc'],['cache-hierarchy','kafka-overview'],['memory-addressing','vm'],['memory-addressing','buffer'],['memory-addressing','storage-layout'],['memory-addressing','go-gc'],
    ['io-bus','epoll'],['io-bus','fs'],['io-bus','sequential-io'],['io-bus','tcp'],['io-bus','wal'],['number-repr','cpu-pipeline'],
    ['number-repr','storage-layout'],['go-syntax','go-concurrency'],['go-concurrency','epoll'],['go-concurrency','http'],['go-concurrency','redis-lock'],['go-runtime','epoll'],
    ['go-runtime','sched'],['go-runtime','cgroup'],['go-gc','buffer'],['go-testing','go-gc'],['go-testing','go-concurrency'],['go-testing','go-runtime'],
    ['go-stdlib','go-syntax'],['go-stdlib','go-web'],['go-web','http'],['go-web','tcp'],['go-web','lb'],['go-web','distributed-db'],
    ['go-memory','cache-hierarchy'],['go-memory','memory-addressing'],['go-memory','cpu-pipeline'],['go-memory','go-concurrency'],['go-architecture','go-web'],['go-architecture','go-stdlib'],
    ['go-architecture','go-testing'],['go-runtime','go-channel'],['go-runtime','go-escape'],['go-runtime','go-mem-alloc'],['go-gc','go-mem-alloc'],['go-gc','go-escape'],
    ['go-gc','go-syncpool'],['go-concurrency','go-channel'],['go-concurrency','go-context'],['go-concurrency','go-select'],['go-concurrency','go-sync'],['go-concurrency','go-atomic'],
    ['go-concurrency','go-errgroup'],['go-channel','go-select'],['go-channel','go-context'],['go-channel','go-patterns'],['go-select','go-timer'],['go-context','go-errgroup'],
    ['go-context','go-web'],['go-sync','go-atomic'],['go-sync','go-syncpool'],['go-syntax','go-interface'],['go-syntax','go-generics'],['go-syntax','go-error'],
    ['go-interface','go-stdlib'],['go-memory','go-atomic'],['go-memory','go-sync'],['go-unsafe','go-memory'],['go-unsafe','go-gc'],['go-timer','epoll'],
    ['go-context','http'],['go-error','go-web'],['go-sync','redis-lock'],['go-atomic','cache-hierarchy'],['go-mem-alloc','vm'],['go-escape','cpu-pipeline'],
    ['go-patterns','go-web'],['go-web','epoll'],['go-web','zero-copy'],['go-json','go-reflect'],['go-json','go-stdlib'],['go-sql','db'],
    ['go-sql','go-context'],['go-pprof','go-gc'],['go-pprof','go-runtime'],['go-slice-map','go-mem-alloc'],['go-slice-map','hash'],['go-strings-bytes','go-string'],
    ['go-modules','go-architecture'],['mysql-logs','wal'],['mysql-logs','kafka-producer'],['mysql-logs','sequential-io'],['cap-theorem','raft'],['cap-theorem','paxos'],['paxos','distributed-db'],['paxos','raft'],
    ['raft','distributed-db'],['raft','kafka-replica'],['raft','redis-cluster'],['cap-theorem','distributed-db'],['cap-theorem','redis-cluster'],['cap-theorem','redis-lock'],
    ['zero-copy','kafka-overview'],['zero-copy','fs'],['zero-copy','http'],
    ['ai-llm-overview','ai-attention'],['ai-llm-overview','ai-training'],['ai-attention','ai-kv-cache'],['ai-kv-cache','ai-rag'],
    ['ai-rag','ai-agent'],['ai-agent','ai-eval-deploy'],['ai-training','ai-moe'],['ai-moe','ai-kv-cache'],['ai-eval-deploy','ai-rag'],
    ['ai-attention','memory-addressing'],['ai-attention','number-repr'],['ai-kv-cache','cache-hierarchy'],['ai-kv-cache','memory-addressing'],
    ['ai-rag','vector'],['ai-rag','bloom'],['ai-rag','probabilistic-ds'],['ai-rag','db-query-plan'],['ai-agent','go-web'],['ai-agent','http'],
    ['ai-agent','go-context'],['ai-agent','redis-stream'],['ai-training','kafka-overview'],['ai-training','sequential-io'],['ai-training','distributed-db'],
    ['ai-moe','cache-hierarchy'],['ai-moe','cgroup'],['ai-moe','lb'],['ai-eval-deploy','go-testing'],['ai-eval-deploy','go-pprof'],
    ['ai-eval-deploy','kafka-consumer'],['ai-eval-deploy','ebpf'],
    ['sd-short-url','hash'],['sd-short-url','bplus'],['sd-short-url','cache-layers'],['sd-short-url','redis-types'],['sd-short-url','lb'],['sd-short-url','http'],
    ['sd-rate-limiter','sliding-window'],['sd-rate-limiter','redis-types'],['sd-rate-limiter','redis-lock'],['sd-rate-limiter','lb'],['sd-rate-limiter','go-context'],['sd-rate-limiter','congestion'],
    ['sd-distributed-id','redis-types'],['sd-distributed-id','kafka-producer'],['sd-distributed-id','go-atomic'],['sd-distributed-id','consistent-hash'],['sd-distributed-id','go-concurrency'],
    ['sd-push-system','kafka-overview'],['sd-push-system','kafka-group'],['sd-push-system','tcp'],['sd-push-system','epoll'],['sd-push-system','go-channel'],['sd-push-system','go-patterns'],
    ['sd-flash-sale','redis-lock'],['sd-flash-sale','kafka-producer'],['sd-flash-sale','cache-layers'],['sd-flash-sale','go-context'],['sd-flash-sale','lb'],['sd-flash-sale','sliding-window']
  ];
})();
