(function () {
  if (window.GRAPH_NODES) return;

  window.GRAPH_MODULES = {
    algo:    { label: '算法',       color: '#38bdf8' },
    db:      { label: '数据库',     color: '#fbbf24' },
    redis:   { label: 'Redis',      color: '#dc382c' },
    linux:   { label: 'Linux',      color: '#6ee7b7' },
    network: { label: '网络',        color: '#10b981' },
    kafka:   { label: 'Kafka',      color: '#ff6b35' },
    cs:      { label: '组成原理',   color: '#a78bfa' },
    golang:  { label: 'Golang',     color: '#00add8' },
    distributed: { label: '分布式',     color: '#c084fc' },
    ai:      { label: 'AI 系统',     color: '#8b5cf6' },
    'system-design': { label: '系统设计', color: '#f59e0b' },
    'cloud-native': { label: '云原生', color: '#38bdf8' },
    observability: { label: '可观测性', color: '#fb923c' },
    security: { label: '安全基础', color: '#f87171' },
    testing: { label: '测试工程', color: '#4ade80' }
  };

  window.GRAPH_NODES = [
    {id:'algo', label:'数据结构与算法', module:'algo', type:'module', href:'algo/index.html', desc:'排序、树、图、动态规划与工程常用数据结构。'},
    {id:'db', label:'数据库原理', module:'db', type:'module', href:'db/index.html', desc:'从 SQL 解析到索引、事务、日志、缓存和分布式数据库。'},
    {id:'redis', label:'Redis 原理', module:'redis', type:'module', href:'redis/index.html', desc:'内存数据结构、持久化、淘汰策略、集群和分布式锁。'},
    {id:'linux', label:'Linux', module:'linux', type:'module', href:'linux/index.html', desc:'命令、进程、内存、I/O、文件系统和调度器。'},
    {id:'network', label:'计算机网络', module:'network', type:'module', href:'network/index.html', desc:'TCP/IP、HTTP、DNS、TLS、负载均衡和现代 QUIC。'},
    {id:'kafka', label:'Kafka', module:'kafka', type:'module', href:'kafka/index.html', desc:'Producer、Consumer、分区副本、消费者组和现代 KRaft 方向。'},
    {id:'cs', label:'计算机组成原理', module:'cs', type:'module', href:'cs/index.html', desc:'CPU、指令、流水线、缓存层次、内存寻址和 I/O 总线。'},
    {id:'golang', label:'Golang', module:'golang', type:'module', href:'golang/index.html', desc:'35 个专题：GMP 调度、GC、Channel、逃逸分析、内存模型、并发模式和工程实践。'},
    {id:'distributed', label:'分布式系统', module:'distributed', type:'module', href:'distributed/index.html', desc:'CAP、Raft、Paxos、一致性哈希等分布式系统基础概念。'},
    {id:'ai', label:'AI 系统', module:'ai', type:'module', href:'ai/index.html', desc:'从 LLM 原理、推理、RAG、Agent 到训练、MoE、评测和部署的工程化知识。'},
    {id:'system-design', label:'系统设计', module:'system-design', type:'module', href:'system-design/index.html', desc:'短链、限流、分布式 ID、消息推送、秒杀——把算法和中间件组装成真实系统。'},
    {id:'sd-short-url', label:'短链系统', module:'system-design', type:'page', href:'system-design/short-url.html', desc:'URL 哈希、Base62 编码、数据库持久化、Redis 缓存和 302 重定向的完整链路。'},
    {id:'sd-rate-limiter', label:'限流器', module:'system-design', type:'page', href:'system-design/rate-limiter.html', desc:'令牌桶、滑动窗口、分布式限流（Redis Lua）和多级降级策略。'},
    {id:'sd-distributed-id', label:'分布式 ID', module:'system-design', type:'page', href:'system-design/distributed-id.html', desc:'Snowflake 位布局、时钟回拨处理、Leaf 号段模式和多机分配。'},
    {id:'sd-push-system', label:'消息推送系统', module:'system-design', type:'page', href:'system-design/push-system.html', desc:'长连接管理、Kafka 消息分发、扇出写/扇出读、ACK 和重试机制。'},
    {id:'sd-flash-sale', label:'秒杀系统', module:'system-design', type:'page', href:'system-design/flash-sale.html', desc:'流量漏斗、Redis 预扣库存、Kafka 异步下单、降级兜底和数据一致性。'},
    {id:'ai-llm-overview', label:'LLM 基础概念', module:'ai', type:'page', href:'ai/llm-overview.html', desc:'解释 Token、Embedding、预训练、微调、对齐和上下文窗口，是理解 LLM 系统的入口。'},
    {id:'ai-attention', label:'Transformer Attention', module:'ai', type:'page', href:'ai/transformer-attention.html', desc:'用 Q/K/V、Mask、Softmax 和 Multi-Head 动画理解 Transformer 如何聚合上下文。'},
    {id:'ai-kv-cache', label:'推理与 KV Cache', module:'ai', type:'page', href:'ai/inference-kv-cache.html', desc:'展示 Tokenize、Prefill、Decode、Sampling 和 Streaming 的在线推理链路。'},
    {id:'ai-rag', label:'RAG Pipeline', module:'ai', type:'page', href:'ai/rag-pipeline.html', desc:'串起 Chunk、Embedding、向量索引、召回、重排、Prompt 组装和生成。'},
    {id:'ai-agent', label:'Agent Tool Calling', module:'ai', type:'page', href:'ai/agent-tool-calling.html', desc:'解释 Planner、工具调用、Observation、Memory、Guardrail 和停止条件组成的 Agent 循环。'},
    {id:'ai-training', label:'Training Pipeline', module:'ai', type:'page', href:'ai/training-pipeline.html', desc:'展示 Dataset、Tokenize、Batch、Forward、Loss、Backward、Optimizer 和 Checkpoint 的训练主链路。'},
    {id:'ai-moe', label:'Mixture of Experts', module:'ai', type:'page', href:'ai/mixture-of-experts.html', desc:'用 Router、Top-k Expert、容量限制和负载均衡理解 MoE 稀疏激活架构。'},
    {id:'ai-eval-deploy', label:'AI 评测与部署', module:'ai', type:'page', href:'ai/eval-deploy.html', desc:'讲 Golden Set、灰度、观测、成本、延迟、Prompt 版本和回滚组成的上线闭环。'},
    {id:'algo-bubble-sort', label:'冒泡排序', module:'algo', type:'page', href:'algo/bubble-sort.html', desc:'相邻元素比较交换，适合理解排序稳定性和局部有序。'},
    {id:'algo-selection-sort', label:'选择排序', module:'algo', type:'page', href:'algo/selection-sort.html', desc:'每轮选择最小元素放到有序区，展示选择型排序思想。'},
    {id:'algo-insertion-sort', label:'插入排序', module:'algo', type:'page', href:'algo/insertion-sort.html', desc:'维护有序前缀，将新元素插入正确位置。'},
    {id:'algo-merge-sort', label:'归并排序', module:'algo', type:'page', href:'algo/merge-sort.html', desc:'分治拆分再归并有序序列，稳定且复杂度 O(n log n)。'},
    {id:'algo-quick-sort', label:'快速排序', module:'algo', type:'page', href:'algo/quick-sort.html', desc:'基于 pivot 分区的原地排序，是工程中常见的排序基础。'},
    {id:'algo-heap-sort', label:'堆排序', module:'algo', type:'page', href:'algo/heap-sort.html', desc:'利用堆结构反复取最大或最小元素完成排序。'},
    {id:'algo-counting-sort', label:'计数排序', module:'algo', type:'page', href:'algo/counting-sort.html', desc:'用计数数组处理有限整数范围内的线性排序。'},
    {id:'algo-radix-sort', label:'基数排序', module:'algo', type:'page', href:'algo/radix-sort.html', desc:'按位分桶排序，适合固定长度整数或字符串。'},
    {id:'topo', label:'拓扑排序', module:'algo', type:'page', href:'algo/topological-sort.html', desc:'处理 DAG 依赖顺序，常见于任务调度、数据管道和构建依赖。'},
    {id:'binary-search', label:'二分查找', module:'algo', type:'page', href:'algo/binary-search.html', desc:'在有序空间中快速定位边界，是索引查找、范围查询和分片定位的基础。'},
    {id:'kmp', label:'KMP / 字符串匹配', module:'algo', type:'page', href:'algo/kmp.html', desc:'高效字符串匹配思想，可连接日志检索、协议解析和关键字过滤。'},
    {id:'algo-linked-list', label:'链表', module:'algo', type:'page', href:'algo/linked-list.html', desc:'通过指针连接节点，适合理解插入删除和内存局部性取舍。'},
    {id:'algo-stack', label:'栈', module:'algo', type:'page', href:'algo/stack.html', desc:'后进先出结构，连接递归、表达式解析和调用栈。'},
    {id:'algo-queue', label:'队列', module:'algo', type:'page', href:'algo/queue.html', desc:'先进先出结构，连接 BFS、任务调度和消息缓冲。'},
    {id:'heap', label:'堆 / Top-K', module:'algo', type:'page', href:'algo/heap.html', desc:'优先队列、外部排序、调度和 Top-K 的底层结构。'},
    {id:'hash', label:'哈希表 / 哈希索引', module:'algo', type:'page', href:'algo/hash-table.html', desc:'O(1) 平均查找的基础，也是缓存、索引和分片的关键。'},
    {id:'skiplist', label:'跳表', module:'algo', type:'page', href:'algo/skip-list.html', desc:'多层链表的概率平衡结构，Redis 大 ZSet 常见基础。'},
    {id:'algo-bst', label:'二叉搜索树', module:'algo', type:'page', href:'algo/binary-search-tree.html', desc:'通过左右子树有序性支持查找、插入和删除。'},
    {id:'algo-avl', label:'AVL 树', module:'algo', type:'page', href:'algo/avl-tree.html', desc:'严格平衡的二叉搜索树，用旋转控制高度。'},
    {id:'algo-btree', label:'B 树', module:'algo', type:'page', href:'algo/b-tree.html', desc:'多路平衡搜索树，是理解磁盘友好索引的前置结构。'},
    {id:'algo-bplus', label:'算法 B+ 树', module:'algo', type:'page', href:'algo/b-plus-tree.html', desc:'从数据结构角度理解 B+ 树节点、分裂与范围遍历。'},
    {id:'trie', label:'Trie 前缀树', module:'algo', type:'page', href:'algo/trie.html', desc:'前缀匹配结构，可用于 DNS 域名层级、路由匹配、自动补全和字典检索。'},
    {id:'segment-tree', label:'线段树 / 区间聚合', module:'algo', type:'page', href:'algo/segment-tree.html', desc:'维护区间聚合和在线更新，可类比监控窗口、时间序列和区间统计。'},
    {id:'algo-tree-traversal', label:'树遍历', module:'algo', type:'page', href:'algo/tree-traversal.html', desc:'前序、中序、后序和层序遍历帮助理解树结构访问顺序。'},
    {id:'union-find', label:'并查集', module:'algo', type:'page', href:'algo/union-find.html', desc:'高效维护连通分量，可类比集群成员、网络分区和副本组连通性。'},
    {id:'bfs', label:'BFS', module:'algo', type:'page', href:'algo/bfs.html', desc:'逐层扩展的图遍历算法，用于最短跳数、依赖扩散和网络连通性分析。'},
    {id:'dfs', label:'DFS', module:'algo', type:'page', href:'algo/dfs.html', desc:'深度优先遍历可用于环检测、死锁检测、拓扑排序和依赖图分析。'},
    {id:'dijkstra', label:'Dijkstra', module:'algo', type:'page', href:'algo/dijkstra.html', desc:'单源最短路径算法，是理解路由选择、网络代价和服务路径优化的基础。'},
    {id:'algo-bellman-ford', label:'Bellman-Ford', module:'algo', type:'page', href:'algo/bellman-ford.html', desc:'可处理负权边的单源最短路径算法。'},
    {id:'algo-kruskal', label:'Kruskal', module:'algo', type:'page', href:'algo/kruskal.html', desc:'基于并查集构造最小生成树。'},
    {id:'algo-prim', label:'Prim', module:'algo', type:'page', href:'algo/prim.html', desc:'从起点出发，优先队列贪心扩展，与 Kruskal 互补的最小生成树算法。'},
    {id:'algo-knapsack', label:'背包问题', module:'algo', type:'page', href:'algo/knapsack.html', desc:'动态规划经典问题，展示状态与选择的关系。'},
    {id:'algo-lcs', label:'最长公共子序列', module:'algo', type:'page', href:'algo/lcs.html', desc:'用二维动态规划处理序列匹配。'},
    {id:'algo-edit-distance', label:'编辑距离', module:'algo', type:'page', href:'algo/edit-distance.html', desc:'Levenshtein Distance，插入/删除/替换三操作的最小代价，搜索纠错和 diff 工具基础。'},
    {id:'algo-interval-dp', label:'区间 DP', module:'algo', type:'page', href:'algo/interval-dp.html', desc:'外层枚举区间长度，内层枚举分割点，矩阵链乘和合并石子的通用框架。'},
    {id:'algo-lis', label:'最长递增子序列', module:'algo', type:'page', href:'algo/lis.html', desc:'连接动态规划、二分优化和有序边界维护。'},
    {id:'db-architecture', label:'数据库架构', module:'db', type:'page', href:'db/db-architecture.html', desc:'从连接层、解析优化、执行引擎到存储引擎理解数据库整体链路。'},
    {id:'query-path', label:'查询执行路径', module:'db', type:'page', href:'db/query-path.html', desc:'SQL 从客户端到磁盘页的完整执行路径。'},
    {id:'storage-layout', label:'存储布局 / 页', module:'db', type:'page', href:'db/storage-layout.html', desc:'页、区、段和磁盘布局，是 B+ 树、Buffer Pool、WAL 的物理基础。'},
    {id:'buffer', label:'Buffer Pool', module:'db', type:'page', href:'db/buffer-pool.html', desc:'数据库页缓存，和 LRU、脏页、WAL 强相关。'},
    {id:'wal', label:'WAL / Redo', module:'db', type:'page', href:'db/wal.html', desc:'先写日志再写数据页，保证崩溃恢复。'},
    {id:'mysql-logs', label:'MySQL 日志体系', module:'db', type:'page', href:'db/mysql-logs.html', desc:'Redo Log / Binlog 分工、checkpoint 机制和 CDC 数据同步链路。'},
    {id:'bplus', label:'B+ 树', module:'db', type:'page', href:'db/btree-index.html', desc:'数据库主流索引结构，依赖多路平衡树、页和叶子链表。'},
    {id:'db-hash-index', label:'哈希索引', module:'db', type:'page', href:'db/hash-index.html', desc:'通过 hash 映射定位记录，适合等值查询但不适合范围扫描。'},
    {id:'db-query-plan', label:'查询计划', module:'db', type:'page', href:'db/query-plan.html', desc:'优化器选择访问路径、Join 顺序和执行算子的成本模型。'},
    {id:'join', label:'Join 算法', module:'db', type:'page', href:'db/join-algo.html', desc:'Nested Loop、Hash Join、Sort-Merge Join 的执行代价。'},
    {id:'sort', label:'外部排序', module:'db', type:'page', href:'db/external-sort.html', desc:'分块排序与 K 路归并，依赖堆和磁盘 I/O。'},
    {id:'mvcc', label:'MVCC', module:'db', type:'page', href:'db/mvcc.html', desc:'通过版本链和快照读实现读写不阻塞。'},
    {id:'locks', label:'锁 / 死锁', module:'db', type:'page', href:'db/transaction.html', desc:'两阶段锁、等待图和 DFS 环检测。'},
    {id:'distributed-db', label:'分布式数据库', module:'db', type:'page', href:'db/distributed-db.html', desc:'CAP、Raft、分片和副本，和 Kafka ISR、网络分区、一致性语义相互关联。'},
    {id:'cache-layers', label:'缓存分层', module:'db', type:'page', href:'db/cache-layers.html', desc:'从浏览器、CDN、应用缓存、Redis 到数据库 Buffer Pool 的多级缓存链路。'},
    {id:'redis-types', label:'Redis 数据类型', module:'redis', type:'page', href:'redis/data-types.html', desc:'String/List/Hash/Set/ZSet 与 listpack、quicklist、skiplist。'},
    {id:'redis-persistence', label:'Redis 持久化', module:'redis', type:'page', href:'redis/persistence.html', desc:'RDB、AOF、rewrite 与 fsync 策略，和 WAL、Page Cache、顺序写相关。'},
    {id:'redis-eviction', label:'Redis 淘汰策略', module:'redis', type:'page', href:'redis/eviction.html', desc:'LRU、LFU、TTL 与内存上限控制。'},
    {id:'redis-cluster', label:'Redis Cluster', module:'redis', type:'page', href:'redis/cluster.html', desc:'槽位分片、主从复制和故障转移，和一致性、网络分区、客户端路由相关。'},
    {id:'redis-lock', label:'Redis 分布式锁', module:'redis', type:'page', href:'redis/distributed-lock.html', desc:'SET NX PX、Lua 原子释放、Redlock 与一致性边界。'},
    {id:'epoll', label:'epoll / I/O 多路复用', module:'linux', type:'page', href:'linux/io-models.html', desc:'高并发服务器和 Redis 单线程事件循环的系统基础。'},
    {id:'vm', label:'虚拟内存 / mmap', module:'linux', type:'page', href:'linux/virtual-memory.html', desc:'页表、TLB、缺页异常、mmap 与数据库页缓存有关。'},
    {id:'fs', label:'VFS / inode', module:'linux', type:'page', href:'linux/filesystem.html', desc:'文件系统抽象，和 WAL、日志文件、零拷贝链路相关。'},
    {id:'sched', label:'CFS / EEVDF', module:'linux', type:'page', href:'linux/scheduling.html', desc:'进程调度、公平性和延迟优化。'},
    {id:'linux-commands', label:'Linux 常用命令', module:'linux', type:'page', href:'linux/commands.html', desc:'ps、ss、df、du、curl、grep 等命令连接进程、网络、磁盘和日志排障。'},
    {id:'linux-process', label:'进程生命周期', module:'linux', type:'page', href:'linux/process-lifecycle.html', desc:'进程创建、运行、阻塞、退出和回收的生命周期。'},
    {id:'tcp', label:'TCP 握手', module:'network', type:'page', href:'network/tcp-handshake.html', desc:'连接建立、关闭、TIME_WAIT 和可靠传输基础。'},
    {id:'congestion', label:'拥塞控制', module:'network', type:'page', href:'network/tcp-congestion.html', desc:'慢启动、拥塞避免、CUBIC、BBR 与网络吞吐。'},
    {id:'http', label:'HTTP/2 / HTTP/3', module:'network', type:'page', href:'network/http.html', desc:'HTTP 演进、TLS 1.3、QUIC 和队头阻塞。'},
    {id:'dns', label:'DNS / CDN', module:'network', type:'page', href:'network/dns.html', desc:'域名解析、缓存、TTL 和边缘调度。'},
    {id:'lb', label:'负载均衡', module:'network', type:'page', href:'network/load-balancing.html', desc:'四层/七层负载均衡、健康检查、会话保持和反向代理。'},
    {id:'kafka-overview', label:'Kafka 存储模型', module:'kafka', type:'page', href:'kafka/kafka-overview.html', desc:'Topic、Partition、Segment、Offset、顺序写和 Page Cache 构成 Kafka 高吞吐基础。'},
    {id:'kafka-producer', label:'Kafka Producer', module:'kafka', type:'page', href:'kafka/producer.html', desc:'Batch、linger.ms、acks、幂等性和吞吐延迟权衡。'},
    {id:'kafka-consumer', label:'Kafka Consumer', module:'kafka', type:'page', href:'kafka/consumer.html', desc:'Offset、提交语义、消费组和 Exactly Once 边界。'},
    {id:'kafka-replica', label:'Partition / ISR', module:'kafka', type:'page', href:'kafka/partition-replication.html', desc:'分区、副本、ISR、Leader 选举与高可用。'},
    {id:'kafka-group', label:'Consumer Group', module:'kafka', type:'page', href:'kafka/consumer-group.html', desc:'Rebalance、分区分配和消费扩展。'},
    {id:'cpu-pipeline', label:'CPU 指令 / 流水线', module:'cs', type:'page', href:'cs/cpu.html', desc:'取指、译码、执行、流水线、分支预测和乱序执行。'},
    {id:'cache-hierarchy', label:'Cache 层次 / 缓存行', module:'cs', type:'page', href:'cs/cache.html', desc:'L1/L2/L3、缓存行、局部性和 false sharing 的硬件基础。'},
    {id:'memory-addressing', label:'内存寻址 / TLB', module:'cs', type:'page', href:'cs/memory.html', desc:'虚拟地址、页表、MMU、TLB 和物理内存访问链路。'},
    {id:'io-bus', label:'总线 / 中断 / DMA', module:'cs', type:'page', href:'cs/io.html', desc:'设备和 CPU 之间通过总线、中断、DMA 进行高效协作。'},
    {id:'number-repr', label:'补码 / IEEE 754', module:'cs', type:'page', href:'cs/number.html', desc:'整数补码表示和 IEEE 754 浮点数格式，理解溢出和精度陷阱的底层原因。'},
    {id:'cs-barrier', label:'内存屏障', module:'cs', type:'page', href:'cs/barrier.html', desc:'Store/Load barrier、mfence、Go 内存模型的硬件根源。'},
    {id:'cs-atomic', label:'原子指令', module:'cs', type:'page', href:'cs/atomic.html', desc:'CAS、LL/SC、x86 LOCK 前缀，sync/atomic 底层实现。'},
    {id:'go-syntax', label:'Go 类型系统', module:'golang', type:'page', href:'golang/type-system.html', desc:'类型、方法集、接口、泛型和显式错误处理。'},
    {id:'go-string', label:'字符串', module:'golang', type:'page', href:'golang/string.html', desc:'字符串不可变、UTF-8、rune 和底层字节序列。'},
    {id:'go-interface', label:'Interface', module:'golang', type:'page', href:'golang/interface.html', desc:'隐式满足、nil interface 陷阱、iface/eface 内部结构。'},
    {id:'go-embedding', label:'嵌入组合', module:'golang', type:'page', href:'golang/embedding.html', desc:'通过嵌入实现组合式代码复用和方法提升。'},
    {id:'go-error', label:'Error 处理', module:'golang', type:'page', href:'golang/error.html', desc:'error 接口、sentinel、%w 包装、Is/As 展开链和自定义错误类型。'},
    {id:'go-generics', label:'泛型', module:'golang', type:'page', href:'golang/generics.html', desc:'type param、约束、any/comparable 和泛型适用场景。'},
    {id:'go-closure', label:'闭包', module:'golang', type:'page', href:'golang/closure.html', desc:'闭包捕获变量、生命周期和逃逸分析关系。'},
    {id:'go-defer-panic', label:'defer / panic / recover', module:'golang', type:'page', href:'golang/defer-panic.html', desc:'defer 执行顺序、panic 传播和 recover 边界。'},
    {id:'go-slice-map', label:'切片与 Map', module:'golang', type:'page', href:'golang/slice-map.html', desc:'slice header、扩容、map bucket 和并发安全边界。'},
    {id:'go-reflect', label:'反射', module:'golang', type:'page', href:'golang/reflect.html', desc:'Type/Value、运行时元信息和动态调用成本。'},
    {id:'go-runtime', label:'GMP 调度器', module:'golang', type:'page', href:'golang/gmp.html', desc:'G、M、P、work stealing、syscall 阻塞和 netpoller。'},
    {id:'go-gc', label:'Go GC', module:'golang', type:'page', href:'golang/gc.html', desc:'并发三色标记、写屏障、堆分配和 pprof 诊断。'},
    {id:'go-channel', label:'Channel', module:'golang', type:'page', href:'golang/channel.html', desc:'无缓冲/有缓冲 channel、close 语义、select 多路复用和 goroutine 协作模式。'},
    {id:'go-concurrency', label:'Goroutine', module:'golang', type:'page', href:'golang/goroutine.html', desc:'goroutine、channel、context 和 sync 包组成 Go 并发模型。'},
    {id:'go-mem-alloc', label:'内存分配器', module:'golang', type:'page', href:'golang/memory-alloc.html', desc:'mcache → mcentral → mheap 三级分配链路与大对象路径。'},
    {id:'go-escape', label:'逃逸分析', module:'golang', type:'page', href:'golang/escape.html', desc:'编译期决定变量在栈还是堆分配，栈分配零 GC 压力。'},
    {id:'go-select', label:'Select', module:'golang', type:'page', href:'golang/select.html', desc:'多路 channel 等待、default 非阻塞、time.After 超时模式。'},
    {id:'go-context', label:'Context', module:'golang', type:'page', href:'golang/context.html', desc:'WithCancel/WithTimeout/WithValue 取消树，控制 goroutine 生命周期。'},
    {id:'go-timer', label:'Timer/Ticker', module:'golang', type:'page', href:'golang/timer.html', desc:'time.Timer 与 Ticker 机制、Reset 竞态、goroutine 泄漏陷阱。'},
    {id:'go-patterns', label:'并发模式', module:'golang', type:'page', href:'golang/concurrent-patterns.html', desc:'pipeline、fan-out/fan-in、worker pool 的 channel 组合模式。'},
    {id:'go-memory', label:'Go 内存模型 / 同步', module:'golang', type:'page', href:'golang/memory-model.html', desc:'happens-before、Mutex、channel、atomic、data race 和 false sharing。'},
    {id:'go-sync', label:'Sync 原语', module:'golang', type:'page', href:'golang/sync.html', desc:'Mutex/RWMutex/WaitGroup/Once/Cond 使用模式与死锁场景。'},
    {id:'go-atomic', label:'Atomic', module:'golang', type:'page', href:'golang/atomic.html', desc:'原子操作、CAS、内存序和与 Mutex 的边界选择。'},
    {id:'go-syncpool', label:'sync.Pool', module:'golang', type:'page', href:'golang/syncpool.html', desc:'对象复用池、GC 回收时机和减少 GC 压力的使用场景。'},
    {id:'go-errgroup', label:'errgroup', module:'golang', type:'page', href:'golang/errgroup.html', desc:'结构化并发、goroutine 错误收集与 WaitGroup 的关系。'},
    {id:'go-stdlib', label:'io.Reader / io.Writer', module:'golang', type:'page', href:'golang/io.html', desc:'package 边界、context、io.Reader/Writer、error wrapping 和标准库资源生命周期。'},
    {id:'go-web', label:'Go Web / RPC 服务', module:'golang', type:'page', href:'golang/http.html', desc:'net/http、middleware、handler/service/repo 分层、超时、连接池和优雅退出。'},
    {id:'go-json', label:'encoding/json', module:'golang', type:'page', href:'golang/json.html', desc:'JSON 编解码、标签、零值和性能优化。'},
    {id:'go-sql', label:'database/sql', module:'golang', type:'page', href:'golang/sql.html', desc:'连接池、事务、预处理和上下文取消。'},
    {id:'go-strings-bytes', label:'strings / bytes', module:'golang', type:'page', href:'golang/strings-bytes.html', desc:'字符串、字节切片和转换成本。'},
    {id:'go-modules', label:'Go Modules', module:'golang', type:'page', href:'golang/modules.html', desc:'模块版本、依赖解析和可复现构建。'},
    {id:'go-testing', label:'Go 测试', module:'golang', type:'page', href:'golang/testing.html', desc:'table-driven test、benchmark、race detector 和 pprof 组成质量闭环。'},
    {id:'go-pprof', label:'pprof 性能分析', module:'golang', type:'page', href:'golang/pprof.html', desc:'CPU、内存、阻塞和 goroutine profile 定位性能瓶颈。'},
    {id:'go-architecture', label:'Go 服务架构', module:'golang', type:'page', href:'golang/patterns.html', desc:'cmd/main、handler、service、repo、infra、配置和可观测性的工程边界。'},
    {id:'go-unsafe', label:'unsafe', module:'golang', type:'page', href:'golang/unsafe.html', desc:'unsafe.Pointer 用法、uintptr 与 GC 的关系和底层内存操作。'},
    {id:'sliding-window', label:'滑动窗口', module:'algo', type:'page', href:'algo/sliding-window.html', desc:'连续窗口内增量维护状态，是限流、TCP 拥塞窗口、流式统计的基础模式。'},
    {id:'monotonic', label:'单调队列 / 栈', module:'algo', type:'page', href:'algo/monotonic.html', desc:'维护候选集合单调性，用于窗口最值、监控峰值和实时指标计算。'},
    {id:'probabilistic-ds', label:'近似数据结构', module:'algo', type:'page', href:'algo/probabilistic-ds.html', desc:'Bloom、HLL、Count-Min Sketch 用可控误差换内存，适合海量判重、基数和频率估计。'},
    {id:'heavy-hitters', label:'Top-K / Heavy Hitters', module:'algo', type:'page', href:'algo/heavy-hitters.html', desc:'用堆、哈希和近似计数发现热点数据，连接热 key、日志分析、告警和推荐。'},
    {id:'consistent-hash', label:'一致性哈希', module:'distributed', type:'page', href:'distributed/consistent-hash.html', desc:'把 key 映射到环上，减少扩缩容时的数据迁移，是缓存、分片、负载均衡的经典算法。'},
    {id:'lru-lfu', label:'LRU / LFU', module:'redis', type:'page', href:'redis/lru-lfu.html', desc:'缓存淘汰算法，连接 Redis 淘汰策略、数据库 Buffer Pool 和多级缓存设计。'},
    {id:'bloom', label:'Bloom Filter', module:'algo', type:'page', href:'algo/bloom.html', desc:'概率型判重结构，适合缓存穿透防护与大规模集合过滤。'},
    {id:'lsm', label:'LSM Tree', module:'db', type:'page', href:'db/lsm.html', desc:'面向写入优化的存储结构，RocksDB/TiKV/LevelDB 生态常见。'},
    {id:'vector', label:'向量索引', module:'db', type:'page', href:'db/vector.html', desc:'HNSW、IVF、PQ 等 ANN 索引是 RAG 与向量数据库基础。'},
    {id:'sequential-io', label:'顺序写 / Page Cache', module:'linux', type:'page', href:'linux/sequential-io.html', desc:'Kafka、WAL、LSM 都依赖顺序写、批量刷盘和 Linux Page Cache 提升吞吐。'},
    {id:'paxos', label:'Paxos', module:'distributed', type:'page', href:'distributed/paxos.html', desc:'Multi-Paxos 是分布式一致性的理论原型，Raft 是其工程简化版。'},
    {id:'raft', label:'Raft', module:'distributed', type:'page', href:'distributed/raft.html', desc:'Leader 选举、日志复制和成员变更，是 etcd、TiKV 和 KRaft 的分布式一致性基础。'},
    {id:'cap-theorem', label:'CAP 定理', module:'distributed', type:'page', href:'distributed/cap-theorem.html', desc:'分布式系统在一致性、可用性、分区容忍性三者间的权衡。'},
    {id:'zero-copy', label:'零拷贝', module:'linux', type:'page', href:'linux/zero-copy.html', desc:'sendfile / mmap 减少内核态与用户态数据拷贝，是 Kafka 高吞吐和 HTTP 文件服务的核心优化。'},
    {id:'ebpf', label:'eBPF', module:'linux', type:'page', href:'linux/ebpf.html', desc:'现代 Linux 可观测、网络和安全能力的核心技术。'},
    {id:'cgroup', label:'cgroup / Namespace', module:'linux', type:'page', href:'linux/cgroup.html', desc:'容器资源限制和隔离的系统基础。'},
    {id:'quic', label:'QUIC', module:'network', type:'page', href:'network/quic.html', desc:'UDP 上的现代传输协议，内置 TLS 1.3、连接迁移和独立流。'},
    {id:'kraft', label:'KRaft', module:'kafka', type:'page', href:'kafka/kraft.html', desc:'Kafka 元数据管理的新模式，逐步替代 ZooKeeper。'},
    {id:'exactly-once', label:'Exactly Once', module:'kafka', type:'page', href:'kafka/exactly-once.html', desc:'幂等 Producer、事务和 offset 原子提交组合出的端到端处理语义。'},
    {id:'redis-stream', label:'Redis Stream', module:'redis', type:'page', href:'redis/redis-stream.html', desc:'Stream 日志带+ConsumerGroup 游标+PEL 确认列表，带消费者组和 ACK 的消息流结构。'},
    {id:'tls', label:'TLS 1.3', module:'network', type:'page', href:'network/tls.html', desc:'TLS 1.3 握手、证书链验证、前向安全和 0-RTT 复用，是 HTTPS/gRPC/QUIC 的加密基础。'},
    {id:'websocket', label:'WebSocket', module:'network', type:'page', href:'network/websocket.html', desc:'HTTP Upgrade 握手、全双工帧传输和心跳机制，适合实时通信场景。'},
    {id:'grpc', label:'gRPC / Protobuf', module:'network', type:'page', href:'network/grpc.html', desc:'HTTP/2 多路复用、Protobuf 二进制序列化和四种流 RPC 模式，是微服务间通信的主流选择。'},
    {id:'http2', label:'HTTP/2', module:'network', type:'page', href:'network/http2.html', desc:'二进制帧、多路复用、HPACK 头部压缩，解决 HTTP/1.1 应用层队头阻塞。'},
    {id:'dist-2pc', label:'两阶段提交', module:'distributed', type:'page', href:'distributed/2pc.html', desc:'Prepare/Commit 两阶段原子提交协议，协调者单点和参与者阻塞是其核心局限。'},
    {id:'saga', label:'Saga 模式', module:'distributed', type:'page', href:'distributed/saga.html', desc:'通过补偿事务实现最终一致性的分布式事务模式，避免 2PC 全局锁。'},
    {id:'zookeeper', label:'ZooKeeper', module:'distributed', type:'page', href:'distributed/zookeeper.html', desc:'ZAB 协议驱动的分布式协调服务，提供强一致的 znode 树和 Watch 通知。'},
    {id:'gossip', label:'Gossip 协议', module:'distributed', type:'page', href:'distributed/gossip.html', desc:'随机选邻居传播信息，O(log N) 轮覆盖全集群，天然容错的成员状态同步机制。'},
    {id:'crdt', label:'CRDT', module:'distributed', type:'page', href:'distributed/crdt.html', desc:'无冲突复制数据类型，任何副本接收到所有操作后状态相同，无需协调。'},
    {id:'base-theory', label:'BASE 理论', module:'distributed', type:'page', href:'distributed/base.html', desc:'基本可用、软状态、最终一致性——AP 分布式系统的设计哲学，是 ACID 的对立面。'},
    {id:'sd-feed-system', label:'信息流系统', module:'system-design', type:'page', href:'system-design/feed-system.html', desc:'推模式/拉模式/混合扇出策略，用 Redis sorted set 和 Kafka 构建低延迟 Timeline。'},
    {id:'sd-chat-system', label:'即时通讯系统', module:'system-design', type:'page', href:'system-design/chat-system.html', desc:'WebSocket 长连接管理、消息顺序 ID、收件箱和离线推送的完整 IM 架构。'},
    {id:'sd-search-suggest', label:'搜索自动补全', module:'system-design', type:'page', href:'system-design/search-suggest.html', desc:'前缀 Trie/Redis sorted set、候选词排分和实时热词聚合，100ms 内返回补全结果。'},
    {id:'sd-object-storage', label:'对象存储', module:'system-design', type:'page', href:'system-design/object-storage.html', desc:'分块上传、纠删码副本、元数据分离和 GC 机制，是 S3/OSS 的核心设计模式。'},
    {id:'sd-task-scheduler', label:'分布式任务调度', module:'system-design', type:'page', href:'system-design/task-scheduler.html', desc:'时间轮 O(1) 触发、分布式分片和幂等执行，保证任务准时不重复地执行。'},
    {id:'sd-geo-service', label:'地理位置服务', module:'system-design', type:'page', href:'system-design/geo-service.html', desc:'GeoHash 将经纬度编码为可索引字符串，四叉树支持非均匀 POI 分布的范围查询。'},
    {id:'algo-rbt', label:'红黑树', module:'algo', type:'page', href:'algo/red-black-tree.html', desc:'自平衡二叉搜索树，通过颜色和旋转保证 O(log n)，是 Linux CFS/Java TreeMap 的底层结构。'},
    {id:'algo-bit', label:'树状数组 / BIT', module:'algo', type:'page', href:'algo/fenwick-tree.html', desc:'利用 lowbit 高效维护前缀和，查询和更新均为 O(log n)，代码极简。'},
    {id:'algo-floyd', label:'Floyd-Warshall', module:'algo', type:'page', href:'algo/floyd-warshall.html', desc:'三重循环 DP 求全源最短路，可处理负权边，并顺带检测负权环。'},
    {id:'algo-backtracking', label:'回溯算法', module:'algo', type:'page', href:'algo/backtracking.html', desc:'系统枚举解空间树，做选择→递归→撤销选择，剪枝避免无效搜索路径。'},
    {id:'algo-greedy', label:'贪心算法', module:'algo', type:'page', href:'algo/greedy.html', desc:'每步局部最优，贪心选择性质和最优子结构是成立前提，活动选择和霍夫曼编码是经典案例。'},
    {id:'algo-ac', label:'AC 自动机', module:'algo', type:'page', href:'algo/aho-corasick.html', desc:'Trie + KMP fail 指针构成的多模式匹配自动机，一次遍历文本匹配所有模式串。'},
    {id:'ai-fine-tuning', label:'微调 / LoRA', module:'ai', type:'page', href:'ai/fine-tuning.html', desc:'SFT 指令对齐、LoRA 低秩分解参数高效微调，让预训练模型适应特定任务的主要方法。'},
    {id:'ai-rlhf', label:'RLHF', module:'ai', type:'page', href:'ai/rlhf.html', desc:'奖励模型 + PPO 强化学习，通过人类偏好对比数据让模型输出更符合期望。'},
    {id:'ai-quantization', label:'模型量化', module:'ai', type:'page', href:'ai/quantization.html', desc:'INT8/INT4 量化将显存需求降低 4-8x，GPTQ/AWQ 是主流训练后量化方案。'},
    {id:'ai-diffusion', label:'扩散模型', module:'ai', type:'page', href:'ai/diffusion.html', desc:'前向加噪 + 逆向去噪，DDPM 奠定理论基础，Stable Diffusion 结合 CLIP 实现文生图。'},
    {id:'ai-embedding', label:'Embedding 模型', module:'ai', type:'page', href:'ai/embedding.html', desc:'对比学习将文本映射为向量，语义相近距离更近，是语义搜索和 RAG 的向量化基础。'},
    {id:'ai-prompt-eng', label:'Prompt Engineering', module:'ai', type:'page', href:'ai/prompt-engineering.html', desc:'CoT、Few-shot、系统提示等技巧引导 LLM，了解 RAG vs Fine-tuning 的选择边界。'},
    {id:'linux-ipc', label:'进程间通信 / IPC', module:'linux', type:'page', href:'linux/ipc.html', desc:'管道、共享内存、消息队列、信号量各自的语义和性能权衡，是多进程架构的基础。'},
    {id:'linux-signal', label:'信号 / Signal', module:'linux', type:'page', href:'linux/signal.html', desc:'内核异步通知机制，信号产生→传递→处理的生命周期，优雅退出和 core dump 的底层原理。'},
    {id:'linux-netstack', label:'Linux 网络协议栈', module:'linux', type:'page', href:'linux/network-stack.html', desc:'socket→TCP→IP→Netfilter→网卡 DMA 的完整收发包路径，是网络调优和 eBPF 的基础。'},
    {id:'db-replication', label:'MySQL 主从复制', module:'db', type:'page', href:'db/replication.html', desc:'Binlog 传输、GTID 全局事务 ID、半同步复制和复制延迟，读写分离和 CDC 的基础。'},
    {id:'db-explain', label:'EXPLAIN 执行计划', module:'db', type:'page', href:'db/explain.html', desc:'type/key/rows/Extra 字段解读，识别全表扫描和 filesort，SQL 性能优化的主要工具。'},
    {id:'db-conn-pool', label:'数据库连接池', module:'db', type:'page', href:'db/connection-pool.html', desc:'连接复用避免重复握手开销，池大小设置、超时参数和泄漏检测是核心配置项。'},
    // Redis 补充页面
    {id:'redis-pipeline', label:'Redis Pipeline', module:'redis', type:'page', href:'redis/pipeline.html', desc:'批量命令消除 RTT 等待，时间线对比展示 Pipeline 灰色等待段大幅缩短。'},
    {id:'redis-pubsub', label:'Pub/Sub', module:'redis', type:'page', href:'redis/pubsub.html', desc:'发布订阅频道模型和模式匹配，与 Stream 消费语义的对比。'},
    // Distributed 补充页面
    {id:'dist-vector-clock', label:'向量时钟', module:'distributed', type:'page', href:'distributed/vector-clock.html', desc:'多节点向量数组 max 合并，无法比较大小的两个时钟代表并发事件。'},
    {id:'dist-service-discovery', label:'服务注册与发现', module:'distributed', type:'page', href:'distributed/service-discovery.html', desc:'心跳驱动的健康检查、Registry 和 Client 本地缓存最终一致性同步。'},
    {id:'dist-tracing', label:'分布式追踪', module:'distributed', type:'page', href:'distributed/distributed-tracing.html', desc:'瀑布图可视化 Span 嵌套时间关系，traceparent 在服务间传播 TraceID/SpanID。'},
    // System Design 补充页面
    {id:'sd-api-gateway', label:'API Gateway', module:'system-design', type:'page', href:'system-design/api-gateway.html', desc:'认证/限流/路由/熔断串联，每个策略有独立内部状态，请求球逐层通过。'},
    {id:'sd-notification', label:'通知系统', module:'system-design', type:'page', href:'system-design/notification-system.html', desc:'优先级队列多渠道并行、失败重试倒计时和幂等 key 防重复投递。'},
    {id:'sd-webcrawler', label:'网络爬虫', module:'system-design', type:'page', href:'system-design/web-crawler.html', desc:'BFS 向外扩展 URL、Bloom Filter 位数组判重和 robots.txt 过滤。'},
    {id:'sd-video', label:'视频流媒体', module:'system-design', type:'page', href:'system-design/video-streaming.html', desc:'分片并行转码多分辨率、ABR 自适应码率和 CDN 边缘分发。'},
    {id:'sd-payment', label:'支付系统', module:'system-design', type:'page', href:'system-design/payment-system.html', desc:'两阶段预扣确认状态机、幂等键防重复支付和对账任务补偿回滚。'},
    {id:'sd-monitoring', label:'监控系统', module:'system-design', type:'page', href:'system-design/metrics-monitoring.html', desc:'TSDB 时序列存块、Alertmanager 聚合抑制和多维指标采集流水线。'},
    // AI 补充页面
    {id:'ai-tokenization', label:'BPE 分词', module:'ai', type:'page', href:'ai/tokenization.html', desc:'字节对编码迭代合并高频相邻对，词表从数据统计中生成。'},
    {id:'ai-llm-serving', label:'LLM 推理服务', module:'ai', type:'page', href:'ai/llm-serving.html', desc:'PagedAttention 分页显存管理消除碎片，连续批处理提升 GPU 利用率。'},
    {id:'ai-multimodal', label:'多模态 AI', module:'ai', type:'page', href:'ai/multimodal.html', desc:'CLIP 对齐视觉语言、跨模态注意力和扩散模型生成多类型内容。'},
    {id:'ai-context-length', label:'长上下文 LLM', module:'ai', type:'page', href:'ai/context-length.html', desc:'RoPE 位置编码外推、KV Cache 压缩和 Lost in the Middle 长文本注意力问题。'},
    // Network 补充页面
    {id:'network-cdn', label:'CDN', module:'network', type:'page', href:'network/cdn.html', desc:'地理就近 PoP 节点、GSLB 路由和 TTL 驱动的缓存命中/回源策略。'},
    {id:'network-nat', label:'NAT', module:'network', type:'page', href:'network/nat.html', desc:'SNAT/DNAT 地址转换、NAT 类型和 STUN/TURN/ICE 穿透机制。'},
    {id:'network-bgp', label:'BGP', module:'network', type:'page', href:'network/bgp.html', desc:'路径向量协议、AS 路由策略（LOCAL_PREF/AS_PATH/MED）和 RPKI 防劫持。'},
    // Linux 补充页面
    {id:'linux-container', label:'容器原理', module:'linux', type:'page', href:'linux/container.html', desc:'Namespace+Cgroup+OverlayFS 三层组合实现隔离，容器不是虚拟机。'},
    {id:'linux-perf', label:'性能工具', module:'linux', type:'page', href:'linux/perf-tools.html', desc:'USE 方法论指导 perf/eBPF/bpftrace 系统性定位 CPU/内存/IO 瓶颈。'},
    {id:'linux-systemd', label:'Systemd', module:'linux', type:'page', href:'linux/systemd.html', desc:'PID 1 服务管理、Unit 依赖图、socket activation 和 cgroup 集成。'},
    // DB 补充页面
    {id:'db-sharding', label:'分库分表', module:'db', type:'page', href:'db/sharding.html', desc:'哈希分片路由单 shard、scatter-gather 跨 shard 代价和在线再平衡双写迁移。'},
    {id:'db-fulltext', label:'全文检索', module:'db', type:'page', href:'db/full-text-search.html', desc:'倒排索引构建 posting list、双指针归并交集和 BM25 TF-IDF 相关性打分。'},
    // CS 补充页面
    {id:'cs-branch', label:'分支预测', module:'cs', type:'page', href:'cs/branch-prediction.html', desc:'流水线投机执行、预测失败 flush 代价和两位饱和计数器状态机。'},
    {id:'cs-tlb', label:'TLB', module:'cs', type:'page', href:'cs/tlb.html', desc:'虚拟地址 VPN+Offset 拆分，TLB hit 1次访存 vs miss 四级页表遍历 5次。'},
    {id:'cs-numa', label:'NUMA', module:'cs', type:'page', href:'cs/numa.html', desc:'跨 NUMA 节点访存延迟 2-3x，numactl 绑定优化和 false sharing 隔离。'},
    // Algo 补充页面
    {id:'algo-maxflow', label:'最大流', module:'algo', type:'page', href:'algo/max-flow.html', desc:'增广路算法和残差图，正向流量增加时反向边同步变化的 Ford-Fulkerson 机制。'},
    {id:'algo-strhash', label:'字符串哈希', module:'algo', type:'page', href:'algo/string-hashing.html', desc:'Rabin-Karp 滚动哈希 O(1) 移动窗口，哈希碰撞时回退逐字符对比。'},
    {id:'algo-bitmanip', label:'位运算', module:'algo', type:'page', href:'algo/bit-manipulation.html', desc:'AND/OR/XOR 基本操作、Brian Kernighan 清最低位和状态压缩 DP 用位表示集合。'},
    {id:'algo-twoptr', label:'双指针', module:'algo', type:'page', href:'algo/two-pointers.html', desc:'对撞指针/快慢指针/滑动窗口/归并四种模式将 O(n²) 降至 O(n)。'},
    {id:'algo-dc', label:'分治', module:'algo', type:'page', href:'algo/divide-conquer.html', desc:'主定理分析递推式、归并排序求逆序对、矩阵快速幂和 Karatsuba 大整数乘法。'},
    // 云原生模块
    {id:'cloud-native', label:'云原生', module:'cloud-native', type:'module', href:'cloud-native/index.html', desc:'Docker 镜像分层、K8s 控制面、Pod 调度、Service 网络和 HPA 弹性伸缩。'},
    {id:'cn-docker', label:'Docker 镜像分层', module:'cloud-native', type:'page', href:'cloud-native/docker.html', desc:'每条 Dockerfile 指令生成一层，OverlayFS 叠加只读镜像和可写容器层，CoW 写时复制。'},
    {id:'cn-kubernetes', label:'K8s 控制面', module:'cloud-native', type:'page', href:'cloud-native/kubernetes.html', desc:'kubectl apply → API Server 认证鉴权 → etcd Raft → Controller Watch → Scheduler → kubelet。'},
    {id:'cn-scheduling', label:'Pod 调度', module:'cloud-native', type:'page', href:'cloud-native/k8s-scheduling.html', desc:'Filter 淘汰不满足节点（资源/Taint），Score 多插件加权打分，最优节点绑定 Pod。'},
    {id:'cn-networking', label:'Service 网络', module:'cloud-native', type:'page', href:'cloud-native/k8s-networking.html', desc:'ClusterIP 是虚拟 IP，iptables DNAT 规则完成真正的负载均衡转发，VXLAN 跨节点。'},
    {id:'cn-hpa', label:'HPA 弹性伸缩', module:'cloud-native', type:'page', href:'cloud-native/k8s-hpa.html', desc:'metrics-server 提供 CPU 指标，HPA 公式计算目标副本数，冷却期防频繁伸缩。'},
    {id:'cn-serverless', label:'Serverless / FaaS', module:'cloud-native', type:'page', href:'cloud-native/serverless.html', desc:'函数即服务：冷启动分段耗时、scale-to-zero 零成本空闲、并发扩容、事件驱动触发与幂等设计。'},
    {id:'cn-gitops', label:'GitOps / ArgoCD', module:'cloud-native', type:'page', href:'cloud-native/gitops.html', desc:'以 Git 为唯一事实来源，ArgoCD 持续对比 Git 与集群状态，检测 drift 后自动将集群拉回声明状态，可审计可回溯。'},
    {id:'cn-service-mesh', label:'Service Mesh', module:'cloud-native', type:'page', href:'cloud-native/service-mesh.html', desc:'Sidecar 代理（Envoy）拦截所有流量，Istiod 通过 xDS 下发路由/限流/熔断/mTLS 策略，业务代码零改动实现服务治理。'},
    {id:'cn-helm', label:'Helm 包管理', module:'cloud-native', type:'page', href:'cloud-native/helm.html', desc:'K8s 包管理器，Chart 打包多个 Manifest，values.yaml 参数化多环境差异，支持版本控制和一键回滚。'},
    {id:'cn-operator', label:'Kubernetes Operator', module:'cloud-native', type:'page', href:'cloud-native/operator.html', desc:'CRD 描述期望状态，自定义 Controller Reconcile 循环持续将实际状态拉向期望，让 K8s 能管理有状态应用。'},
    {id:'cn-storage', label:'K8s 存储 PV/PVC', module:'cloud-native', type:'page', href:'cloud-native/k8s-storage.html', desc:'StorageClass → CSI Driver 动态创建 PV，PVC 申请绑定，Pod 重调度时数据持久保留，支持在线扩容。'},
    // 可观测性模块
    {id:'observability', label:'可观测性', module:'observability', type:'module', href:'observability/index.html', desc:'Prometheus 指标采集、OpenTelemetry 链路追踪和 SLO Error Budget 管理三大支柱。'},
    {id:'obs-prometheus', label:'Prometheus', module:'observability', type:'page', href:'observability/prometheus.html', desc:'拉取模式 Scrape 每 15s、TSDB 内存块压缩到磁盘和 Alertmanager 规则持续评估。'},
    {id:'obs-tracing', label:'OpenTelemetry 追踪', module:'observability', type:'page', href:'observability/tracing.html', desc:'traceparent 头传播 traceId/spanId，Span 批量 OTLP 上报，瀑布图可视化调用链。'},
    {id:'obs-slo', label:'SLO & Error Budget', module:'observability', type:'page', href:'observability/slo.html', desc:'SLO 目标定义月故障预算，Error Budget 耗尽冻结发布，Burn Rate 预警。'},
    {id:'obs-logging', label:'日志体系 ELK/Loki', module:'observability', type:'page', href:'observability/logging.html', desc:'Fluentd/Promtail 采集 → Elasticsearch/Loki 存储，倒排索引全文检索，Agent 崩溃从 checkpoint 续传不丢日志。'},
    {id:'obs-otel', label:'OpenTelemetry', module:'observability', type:'page', href:'observability/opentelemetry.html', desc:'统一 SDK 采集 Trace/Metric/Log，Collector Pipeline 批量处理和多 Exporter 扇出，Tail Sampling 按完整 Trace 决策。'},
    {id:'obs-grafana', label:'Grafana 与告警', module:'observability', type:'page', href:'observability/grafana.html', desc:'Dashboard 分层设计（USE/RED 方法），Alertmanager 路由/分组/抑制/静默，告警信噪比与 SLO 联动设计。'},
    {id:'obs-chaos', label:'混沌工程', module:'observability', type:'page', href:'observability/chaos.html', desc:'稳态假说 → 注入故障 → 观测偏差 → 修复薄弱点，Chaos Mesh/Monkey 实现 Pod Kill/网络分区/延迟注入。'},
    // 安全基础模块
    {id:'security', label:'安全基础', module:'security', type:'module', href:'security/index.html', desc:'对称非对称加密原理、OAuth 2.0 授权码流程、Web 攻击防御和 JWT 令牌机制。'},
    {id:'sec-crypto', label:'对称/非对称加密', module:'security', type:'page', href:'security/crypto.html', desc:'AES-CBC 链式加密和 RSA 加密/签名方向，加密保机密性，签名保真实性。'},
    {id:'sec-oauth', label:'OAuth 2.0', module:'security', type:'page', href:'security/oauth.html', desc:'授权码流程四角色，Code 一次性后端渠道换 Token，Access Token 有过期时间。'},
    {id:'sec-web-attacks', label:'Web 攻击', module:'security', type:'page', href:'security/web-attacks.html', desc:'SQL 注入代码数据混淆、XSS 输出编码防御和 CSRF SameSite Cookie+Token 双重防御。'},
    {id:'sec-jwt', label:'JWT', module:'security', type:'page', href:'security/jwt.html', desc:'三段 Base64 结构解析、HMAC-SHA256 签名验证流程和 alg:none 安全漏洞说明。'},
    {id:'sec-pki', label:'PKI 与证书体系', module:'security', type:'page', href:'security/pki.html', desc:'CA 层级签发证书链，浏览器从叶证书向上逐层验证到根 CA，ACME 自动续签，OCSP 吊销检查。'},
    {id:'sec-secrets', label:'密钥管理 Vault', module:'security', type:'page', href:'security/secrets.html', desc:'Vault 动态凭据：服务请求后生成一次性账号（TTL），到期自动销毁，凭据不持久存在，自动轮换消除静态密码。'},
    {id:'sec-container', label:'容器安全', module:'security', type:'page', href:'security/container-security.html', desc:'镜像 CVE 扫描（Trivy），securityContext 限制权限，Seccomp/AppArmor 限制 syscall，K8s RBAC 最小权限原则。'},
    {id:'sec-supply-chain', label:'供应链安全', module:'security', type:'page', href:'security/supply-chain.html', desc:'SBOM 软件物料清单，Cosign 对镜像摘要签名，K8s Admission Webhook 强制验签，防止构建链污染。'},
    {id:'sec-zero-trust', label:'零信任网络', module:'security', type:'page', href:'security/zero-trust.html', desc:'Never Trust Always Verify：每次访问经过身份认证+设备健康检查+最小权限授权，mTLS 服务间双向验证。'},
    // 算法模块新增
    {id:'algo-prim', label:'Prim 最小生成树', module:'algo', type:'page', href:'algo/prim.html', desc:'从起始节点出发，每步从已选节点相邻边中贪心选最小权重边，配合优先队列 O(E log V)，适合稠密图。'},
    {id:'algo-edit-distance', label:'编辑距离', module:'algo', type:'page', href:'algo/edit-distance.html', desc:'DP 二维表格：dp[i][j] = min(替换/插入/删除)，回溯还原操作序列，搜索纠错/diff/DNA 比对的基础。'},
    {id:'algo-interval-dp', label:'区间 DP', module:'algo', type:'page', href:'algo/interval-dp.html', desc:'外层枚举区间长度，内层枚举分割点，dp[i][j] 表示区间最优值。矩阵链乘/合并石子/戳气球的通用模型。'},
    // 数据库模块新增
    {id:'db-timeseries', label:'时序数据库', module:'db', type:'page', href:'db/timeseries.html', desc:'Delta-of-Delta 时间戳压缩和 XOR 浮点编码，时间分区剪枝查询，TTL 整分区 O(1) 删除，降采样降存储压力。'},
    {id:'db-column-store', label:'列存储 ClickHouse', module:'db', type:'page', href:'db/column-store.html', desc:'同列连续存储减少 OLAP 查询 IO，RLE/字典/Delta 列压缩，SIMD 向量化执行，MergeTree 后台合并排序。'},
    {id:'db-graph-db', label:'图数据库', module:'db', type:'page', href:'db/graph-db.html', desc:'节点和关系带直接指针，多跳遍历 O(degree) vs SQL JOIN 指数膨胀，Cypher 路径查询，社交/知识图谱场景。'},
    // 网络模块新增
    {id:'network-ip', label:'IP 协议基础', module:'network', type:'page', href:'network/ip.html', desc:'ARP 解析 IP→MAC，路由表逐跳转发，TTL 递减防循环（Traceroute 原理），CIDR 子网划分与广播域。'},
    {id:'network-vxlan', label:'VXLAN Overlay', module:'network', type:'page', href:'network/vxlan.html', desc:'二层帧封装在 UDP 中，VTEP 封包/解包，VNI 区分租户，EVPN 控制平面分发 MAC-IP 映射，K8s 跨主机 Pod 通信基础。'},
    // 分布式模块新增
    {id:'dist-lease', label:'分布式租约', module:'distributed', type:'page', href:'distributed/lease.html', desc:'TTL 心跳续约保活，到期自动释放，Fencing Token 防脑裂后旧持有者操作资源，惊群效应用随机抖动缓解。'},
    {id:'dist-quorum', label:'Quorum 读写', module:'distributed', type:'page', href:'distributed/quorum.html', desc:'W+R>N 保证读到最新写，读修复异步修复落后副本，W+R=N 时存在脏读风险，Cassandra/DynamoDB 的一致性旋钮。'},
    // AI 模块新增
    {id:'ai-guardrails', label:'AI 安全护栏', module:'ai', type:'page', href:'ai/guardrails.html', desc:'Prompt Injection/越狱攻击模式，多层防御：输入过滤+Prompt 加固+输出检测+审计，Llama Guard 等护栏框架。'},
    {id:'ai-structured-output', label:'结构化输出', module:'ai', type:'page', href:'ai/structured-output.html', desc:'JSON mode 强制输出有效 JSON，Function Calling 返回结构化调用请求，Constrained Decoding 约束 token 选择。'},
    {id:'ai-inference-opt', label:'推理优化', module:'ai', type:'page', href:'ai/inference-optimization.html', desc:'Speculative Decoding 小模型猜大模型验加速 2x，FlashAttention IO 感知分块减少 HBM 访问，PagedAttention 消除显存碎片。'},
    // Linux 模块新增
    {id:'linux-io-uring', label:'io_uring', module:'linux', type:'page', href:'linux/io-uring.html', desc:'SQ/CQ 环形队列批量提交 I/O，一次系统调用处理多个请求，减少用户态/内核态切换，零拷贝固定缓冲区。'},
    {id:'linux-dpdk', label:'DPDK 用户态网络', module:'linux', type:'page', href:'linux/dpdk.html', desc:'PMD 轮询模式绕过内核中断，大页内存减少 TLB miss，用户态直接读写网卡 DMA，千万 pps 级高性能网络处理。'},
    // 系统设计模块新增
    {id:'sd-config-center', label:'配置中心', module:'system-design', type:'page', href:'system-design/config-center.html', desc:'集中管理配置，Long Poll 推送变更，服务热更新不重启，灰度推送按实例分批，宕机时降级读本地缓存。'},
    {id:'sd-multi-region', label:'多活与异地容灾', module:'system-design', type:'page', href:'system-design/multi-region.html', desc:'GSLB 就近路由双 Region，CDC 跨区同步存在延迟窗口，故障切换保 RTO/RPO 指标，仲裁节点防脑裂。'},
    // Golang 模块新增
    {id:'go-cgo', label:'CGO', module:'golang', type:'page', href:'golang/cgo.html', desc:'Go 调用 C 库需切换 goroutine 栈到 OS 线程，约 100ns 额外开销，阻塞 C 调用触发新 M 创建，不支持交叉编译。'},
    {id:'go-build', label:'Go 构建系统', module:'golang', type:'page', href:'golang/build.html', desc:'build tag 条件编译，GOOS/GOARCH 交叉编译，go:generate 代码生成，内容寻址 build cache，go work 多模块工作区。'},
    // AI 模块新增
    {id:'ai-spec-decode', label:'投机解码', module:'ai', type:'page', href:'ai/speculative-decoding.html', desc:'Draft Model 快速生成 token 候选，Target Model 并行验证，接受则保留，拒绝则截断重采样，在不降低输出质量前提下加速推理 2-3x。'},
    {id:'ai-llm-reasoning', label:'LLM 推理增强', module:'ai', type:'page', href:'ai/llm-reasoning.html', desc:'Chain-of-Thought 中间步骤引导推理，Tree-of-Thought 将搜索空间展为树并剪枝，ReAct 交替推理和工具调用，Self-Consistency 多路采样投票提升准确率。'},
    {id:'ai-model-merging', label:'模型融合', module:'ai', type:'page', href:'ai/model-merging.html', desc:'SLERP 球形插值平滑融合参数，Task Arithmetic 用微调 delta 向量加减组合能力，TIES/DARE 稀疏化参数冲突再融合，无需重新训练即可组合多种专业能力。'},
    // Algo 模块新增
    {id:'algo-suffix-array', label:'后缀数组', module:'algo', type:'page', href:'algo/suffix-array.html', desc:'SA-IS 算法线性构建后缀数组，LCP 数组记录相邻后缀最长公共前缀，配合二分查找支持 O(m log n) 子串匹配，是处理复杂字符串问题的高效工具。'},
    {id:'algo-tarjan-scc', label:'Tarjan SCC', module:'algo', type:'page', href:'algo/tarjan-scc.html', desc:'DFS 过程中用时间戳 disc 和 low 值识别回退边，栈弹出同一 SCC 节点，线性时间 O(V+E) 找出所有强连通分量，缩点后形成 DAG 支持后续拓扑排序。'},
    {id:'algo-bipartite', label:'二分图匹配', module:'algo', type:'page', href:'algo/bipartite-matching.html', desc:'匈牙利算法 DFS 寻找增广路交替扩大匹配集，Hopcroft-Karp 分层 BFS 批量找多条不相交增广路，复杂度 O(sqrt(V)·E)，应用于任务分配和网络流。'},
    {id:'algo-hld', label:'树链剖分', module:'algo', type:'page', href:'algo/hld.html', desc:'按子树大小标记重边轻边，将树拆成若干重链，配合线段树实现 O(log²n) 路径查询和修改，是树上高效区间操作的核心技巧。'},
    // System Design 模块新增
    {id:'sd-recommendation', label:'推荐系统', module:'system-design', type:'page', href:'system-design/recommendation.html', desc:'协同过滤/双塔向量召回生成候选集，轻量粗排过滤，精排 DNN 打分，Rerank 多样性调整，实时用户行为特征更新驱动推荐效果迭代。'},
    {id:'sd-live-streaming', label:'直播系统', module:'system-design', type:'page', href:'system-design/live-streaming.html', desc:'主播 RTMP 推流到 Origin，转码集群生成多分辨率 HLS，CDN 边缘节点拉流分发，LLHLS 把端到端延迟压到 2-5 秒，弹幕用 WebSocket 广播同步。'},
    {id:'sd-search-engine', label:'搜索引擎', module:'system-design', type:'page', href:'system-design/search-engine.html', desc:'爬虫并行抓取页面，分词后构建倒排索引，BM25/TF-IDF 相关性打分，PageRank 衡量权威度，分布式 Shard 并行检索后合并排序返回。'},
    // Distributed 模块新增
    {id:'dist-3pc', label:'三阶段提交', module:'distributed', type:'page', href:'distributed/3pc.html', desc:'在 2PC 基础上增加 CanCommit 预备阶段，引入超时机制，协调者故障后参与者可协商自行提交，消除单点阻塞，但仍无法解决网络分区导致的脑裂。'},
    {id:'dist-spanner', label:'Spanner / TrueTime', module:'distributed', type:'page', href:'distributed/spanner.html', desc:'Google Spanner 通过 GPS+原子钟提供有界误差时间戳，commit-wait 等待误差窗口保证外部一致性，Paxos 分组管理分片，支持全球范围强一致事务。'},
    // Golang 新增页面
    {id:'go-perf-tuning', label:'Go 性能调优', module:'golang', type:'page', href:'golang/performance-tuning.html', desc:'系统性调优路径：CPU 火焰图定位热点 → 内存分配减少 heap escape → goroutine 泄漏检测 → mutex 竞争分析，结合 pprof/trace/benchstat 工具链闭环。'},
    {id:'go-assembly', label:'Go 汇编', module:'golang', type:'page', href:'golang/go-assembly.html', desc:'Plan 9 汇编语法、函数调用约定（寄存器传参 ABI）、栈帧结构和伪寄存器（FP/SP/PC/SB），帮助理解 Go 编译器输出和手写汇编优化的边界。'},
    // CS 模块新增
    {id:'cs-gpu-arch', label:'GPU 架构', module:'cs', type:'page', href:'cs/gpu-architecture.html', desc:'SM/Warp/SIMT 并行执行模型，显存层次 L1/L2/HBM 带宽差异，Warp 分叉导致效率下降，CPU-GPU 通过 PCIe 协作，是深度学习推理的算力底座。'},
    // DB 模块新增
    {id:'db-nosql', label:'NoSQL 分类', module:'db', type:'page', href:'db/nosql.html', desc:'文档型（MongoDB）/宽列型（Cassandra）/KV 型（DynamoDB）/图型（Neo4j）四类 NoSQL 的数据模型、CAP 选择、典型场景和关系型数据库选型矩阵。'},
    // 测试工程模块
    {id:'testing', label:'测试工程', module:'testing', type:'module', href:'testing/index.html', desc:'从测试金字塔到负载测试、Mock 技术、契约测试和模糊测试，构建系统性的工程质量体系。'},
    {id:'test-pyramid', label:'测试金字塔', module:'testing', type:'page', href:'testing/test-pyramid.html', desc:'单元/集成/E2E 三层金字塔策略，测试覆盖率原则，隔离边界划分和分布式系统测试挑战。'},
    {id:'test-mock', label:'Mock / Stub / Spy', module:'testing', type:'page', href:'testing/mock-stub.html', desc:'Test Doubles 五种类型对比，接口驱动 Mock 设计，gomock/testify 工程实践和过度 Mock 反模式。'},
    {id:'test-load', label:'负载与压力测试', module:'testing', type:'page', href:'testing/load-testing.html', desc:'并发用户模型、延迟百分位（P50/P95/P99）、吞吐与延迟权衡，k6/wrk 压测工具和瓶颈识别方法论。'},
    {id:'test-contract', label:'契约测试', module:'testing', type:'page', href:'testing/contract-testing.html', desc:'Consumer-Driven Contract 以消费者期望约束 Provider 接口，Pact 框架实现微服务解耦测试，避免集成环境依赖。'},
    {id:'test-fuzz', label:'模糊测试', module:'testing', type:'page', href:'testing/fuzz-testing.html', desc:'Coverage-guided fuzzing 自动探索边界输入，Go 原生 go test -fuzz 用法，Corpus 语料库管理和工程价值。'},
    {id:'test-tdd', label:'TDD / BDD', module:'testing', type:'page', href:'testing/tdd.html', desc:'Red-Green-Refactor 循环驱动设计，测试先行减少过度设计，BDD 行为描述连接业务语义和代码实现。'}
  ];

  window.GRAPH_EDGES = [
    ['cs-barrier','go-memory'],['cs-atomic','go-atomic'],['cache-hierarchy','cs-barrier'],['bplus','algo-bplus'],['bplus','buffer'],['bplus','vm'],
    ['bplus','storage-layout'],['bplus','binary-search'],['binary-search','storage-layout'],['binary-search','redis-types'],['hash','redis-types'],['hash','join'],
    ['hash','redis-eviction'],['hash','redis-cluster'],['hash','kafka-producer'],['hash','consistent-hash'],['hash','bloom'],['hash','db-hash-index'],
    ['skiplist','redis-types'],['skiplist','binary-search'],['heap','sort'],['heap','sched'],['heap','heavy-hitters'],['heap','algo-heap-sort'],
    ['bfs','dfs'],['bfs','dijkstra'],['dfs','locks'],['dfs','topo'],['dijkstra','lb'],['union-find','distributed-db'],
    ['union-find','redis-cluster'],['union-find','kafka-replica'],['topo','kafka-overview'],['topo','distributed-db'],['trie','dns'],['trie','http'],
    ['trie','lb'],['trie','kmp'],['kmp','linux-commands'],['sliding-window','congestion'],['sliding-window','tcp'],['sliding-window','http'],
    ['sliding-window','lb'],['sliding-window','heavy-hitters'],['sliding-window','kafka-consumer'],['monotonic','sliding-window'],['monotonic','segment-tree'],['monotonic','heavy-hitters'],
    ['probabilistic-ds','bloom'],['probabilistic-ds','redis-stream'],['probabilistic-ds','vector'],['probabilistic-ds','heavy-hitters'],['heavy-hitters','cache-layers'],['heavy-hitters','kafka-consumer'],
    ['consistent-hash','distributed-db'],['consistent-hash','lb'],['consistent-hash','cache-layers'],['consistent-hash','kafka-group'],['lru-lfu','redis-eviction'],['lru-lfu','buffer'],
    ['lru-lfu','cache-layers'],['bloom','cache-layers'],['bloom','vector'],['db-architecture','query-path'],['query-path','db-query-plan'],['query-path','buffer'],
    ['query-path','wal'],['query-path','mvcc'],['db-query-plan','join'],['db-query-plan','sort'],['buffer','wal'],['buffer','vm'],
    ['buffer','redis-eviction'],['buffer','cache-layers'],['wal','fs'],['wal','mvcc'],['wal','sequential-io'],['mvcc','locks'],
    ['mvcc','distributed-db'],['sort','sequential-io'],['storage-layout','fs'],['storage-layout','vm'],['cache-layers','redis-eviction'],['cache-layers','dns'],
    ['distributed-db','locks'],['distributed-db','kafka-replica'],['distributed-db','redis-cluster'],['lsm','wal'],['lsm','sequential-io'],['lsm','distributed-db'],
    ['redis-types','redis-stream'],['redis-persistence','wal'],['redis-persistence','fs'],['redis-persistence','sequential-io'],['redis-lock','locks'],['epoll','redis-types'],
    ['epoll','http'],['epoll','tcp'],['epoll','kafka-consumer'],['linux-commands','epoll'],['linux-commands','tcp'],['linux-commands','fs'],
    ['linux-commands','redis-persistence'],['linux-commands','kafka-overview'],['linux-process','sched'],['fs','kafka-overview'],['fs','sequential-io'],['vm','kafka-overview'],
    ['vm','sequential-io'],['ebpf','tcp'],['ebpf','kafka-consumer'],['cgroup','sched'],['cgroup','kafka-consumer'],['tcp','http'],
    ['tcp','kafka-producer'],['tcp','kafka-consumer'],['tcp','kafka-replica'],['congestion','http'],['congestion','kafka-producer'],['quic','http'],
    ['dns','http'],['dns','lb'],['lb','http'],['lb','kafka-consumer'],['kafka-overview','kafka-producer'],['kafka-overview','kafka-consumer'],
    ['kafka-overview','kafka-replica'],['kafka-overview','sequential-io'],['kafka-overview','wal'],['kafka-overview','lsm'],['kafka-producer','kafka-replica'],['kafka-producer','exactly-once'],
    ['kafka-consumer','kafka-group'],['kafka-consumer','exactly-once'],['kafka-group','redis-stream'],['kafka-replica','kraft'],['kraft','raft'],
    ['cpu-pipeline','sched'],['cpu-pipeline','go-runtime'],['cpu-pipeline','go-gc'],['cache-hierarchy','buffer'],['cache-hierarchy','redis-types'],['cache-hierarchy','lru-lfu'],
    ['cache-hierarchy','go-gc'],['cache-hierarchy','kafka-overview'],['memory-addressing','vm'],['memory-addressing','buffer'],['memory-addressing','storage-layout'],['memory-addressing','go-gc'],
    ['io-bus','epoll'],['io-bus','fs'],['io-bus','sequential-io'],['io-bus','tcp'],['io-bus','wal'],['number-repr','cpu-pipeline'],
    ['number-repr','storage-layout'],['go-syntax','go-concurrency'],['go-concurrency','epoll'],['go-concurrency','http'],['go-concurrency','redis-lock'],['go-runtime','epoll'],
    ['go-runtime','sched'],['go-runtime','cgroup'],['go-gc','buffer'],['go-testing','go-gc'],['go-testing','go-concurrency'],['go-testing','go-runtime'],
    ['go-stdlib','go-syntax'],['go-stdlib','go-web'],['go-web','http'],['go-web','tcp'],['go-web','lb'],['go-web','distributed-db'],
    ['go-memory','cache-hierarchy'],['go-memory','memory-addressing'],['go-memory','cpu-pipeline'],['go-memory','go-concurrency'],['go-architecture','go-web'],['go-architecture','go-stdlib'],
    ['go-architecture','go-testing'],['go-runtime','go-channel'],['go-runtime','go-escape'],['go-runtime','go-mem-alloc'],['go-gc','go-mem-alloc'],['go-gc','go-escape'],
    ['go-gc','go-syncpool'],['go-concurrency','go-channel'],['go-concurrency','go-context'],['go-concurrency','go-select'],['go-concurrency','go-sync'],['go-concurrency','go-atomic'],
    ['go-concurrency','go-errgroup'],['go-channel','go-select'],['go-channel','go-context'],['go-channel','go-patterns'],['go-select','go-timer'],['go-context','go-errgroup'],
    ['go-context','go-web'],['go-sync','go-atomic'],['go-sync','go-syncpool'],['go-syntax','go-interface'],['go-syntax','go-generics'],['go-syntax','go-error'],
    ['go-interface','go-stdlib'],['go-memory','go-atomic'],['go-memory','go-sync'],['go-unsafe','go-memory'],['go-unsafe','go-gc'],['go-timer','epoll'],
    ['go-context','http'],['go-error','go-web'],['go-sync','redis-lock'],['go-atomic','cache-hierarchy'],['go-mem-alloc','vm'],['go-escape','cpu-pipeline'],
    ['go-patterns','go-web'],['go-web','epoll'],['go-web','zero-copy'],['go-json','go-reflect'],['go-json','go-stdlib'],['go-sql','db'],
    ['go-sql','go-context'],['go-pprof','go-gc'],['go-pprof','go-runtime'],['go-slice-map','go-mem-alloc'],['go-slice-map','hash'],['go-strings-bytes','go-string'],
    ['go-modules','go-architecture'],['mysql-logs','wal'],['mysql-logs','kafka-producer'],['mysql-logs','sequential-io'],['cap-theorem','raft'],['cap-theorem','paxos'],['paxos','distributed-db'],['paxos','raft'],
    ['raft','distributed-db'],['raft','kafka-replica'],['raft','redis-cluster'],['cap-theorem','distributed-db'],['cap-theorem','redis-cluster'],['cap-theorem','redis-lock'],
    ['zero-copy','kafka-overview'],['zero-copy','fs'],['zero-copy','http'],
    ['ai-llm-overview','ai-attention'],['ai-llm-overview','ai-training'],['ai-attention','ai-kv-cache'],['ai-kv-cache','ai-rag'],
    ['ai-rag','ai-agent'],['ai-agent','ai-eval-deploy'],['ai-training','ai-moe'],['ai-moe','ai-kv-cache'],['ai-eval-deploy','ai-rag'],
    ['ai-attention','memory-addressing'],['ai-attention','number-repr'],['ai-kv-cache','cache-hierarchy'],['ai-kv-cache','memory-addressing'],
    ['ai-rag','vector'],['ai-rag','bloom'],['ai-rag','probabilistic-ds'],['ai-rag','db-query-plan'],['ai-agent','go-web'],['ai-agent','http'],
    ['ai-agent','go-context'],['ai-agent','redis-stream'],['ai-training','kafka-overview'],['ai-training','sequential-io'],['ai-training','distributed-db'],
    ['ai-moe','cache-hierarchy'],['ai-moe','cgroup'],['ai-moe','lb'],['ai-eval-deploy','go-testing'],['ai-eval-deploy','go-pprof'],
    ['ai-eval-deploy','kafka-consumer'],['ai-eval-deploy','ebpf'],
    ['sd-short-url','hash'],['sd-short-url','bplus'],['sd-short-url','cache-layers'],['sd-short-url','redis-types'],['sd-short-url','lb'],['sd-short-url','http'],
    ['sd-rate-limiter','sliding-window'],['sd-rate-limiter','redis-types'],['sd-rate-limiter','redis-lock'],['sd-rate-limiter','lb'],['sd-rate-limiter','go-context'],['sd-rate-limiter','congestion'],
    ['sd-distributed-id','redis-types'],['sd-distributed-id','kafka-producer'],['sd-distributed-id','go-atomic'],['sd-distributed-id','consistent-hash'],['sd-distributed-id','go-concurrency'],
    ['sd-push-system','kafka-overview'],['sd-push-system','kafka-group'],['sd-push-system','tcp'],['sd-push-system','epoll'],['sd-push-system','go-channel'],['sd-push-system','go-patterns'],
    ['sd-flash-sale','redis-lock'],['sd-flash-sale','kafka-producer'],['sd-flash-sale','cache-layers'],['sd-flash-sale','go-context'],['sd-flash-sale','lb'],['sd-flash-sale','sliding-window'],
    ['tls','http'],['tls','quic'],['tls','grpc'],['websocket','http'],['websocket','epoll'],['websocket','sd-push-system'],
    ['grpc','http2'],['grpc','tls'],['grpc','lb'],['grpc','go-web'],['http2','tls'],['http2','http'],['http2','quic'],
    ['dist-2pc','raft'],['dist-2pc','distributed-db'],['dist-2pc','saga'],['saga','distributed-db'],['saga','kafka-producer'],['saga','base-theory'],
    ['zookeeper','paxos'],['zookeeper','distributed-db'],['zookeeper','cap-theorem'],['gossip','cap-theorem'],['gossip','redis-cluster'],['gossip','consistent-hash'],
    ['crdt','cap-theorem'],['crdt','gossip'],['crdt','base-theory'],['base-theory','cap-theorem'],['base-theory','crdt'],['base-theory','distributed-db'],
    ['sd-feed-system','redis-types'],['sd-feed-system','kafka-overview'],['sd-feed-system','cache-layers'],['sd-feed-system','lb'],
    ['sd-chat-system','websocket'],['sd-chat-system','kafka-overview'],['sd-chat-system','redis-types'],['sd-chat-system','sd-push-system'],
    ['sd-search-suggest','redis-types'],['sd-search-suggest','trie'],['sd-search-suggest','kafka-consumer'],
    ['sd-object-storage','consistent-hash'],['sd-object-storage','cache-layers'],['sd-object-storage','fs'],['sd-object-storage','sequential-io'],
    ['sd-task-scheduler','redis-types'],['sd-task-scheduler','kafka-producer'],['sd-task-scheduler','distributed-db'],['sd-task-scheduler','go-concurrency'],
    ['sd-geo-service','redis-types'],['sd-geo-service','bplus'],['sd-geo-service','cache-layers'],
    ['algo-rbt','bst'],['algo-rbt','bplus'],['algo-bit','dp'],['algo-bit','hash'],
    ['algo-floyd','dp'],['algo-floyd','bfs-dfs'],['algo-backtracking','bfs-dfs'],['algo-backtracking','dp'],
    ['algo-greedy','dp'],['algo-greedy','heap'],['algo-ac','trie'],['algo-ac','kmp'],['algo-ac','bfs-dfs'],
    ['ai-fine-tuning','ai-training'],['ai-fine-tuning','ai-llm-overview'],['ai-rlhf','ai-fine-tuning'],['ai-rlhf','ai-training'],
    ['ai-quantization','ai-llm-overview'],['ai-quantization','ai-fine-tuning'],['ai-diffusion','ai-attention'],['ai-diffusion','ai-training'],
    ['ai-embedding','ai-llm-overview'],['ai-embedding','ai-rag'],['ai-prompt-eng','ai-llm-overview'],['ai-prompt-eng','ai-rag'],['ai-prompt-eng','ai-fine-tuning'],
    ['linux-ipc','vm'],['linux-ipc','linux-signal'],['linux-signal','linux-ipc'],['linux-signal','go-concurrency'],
    ['linux-netstack','epoll'],['linux-netstack','tcp'],['linux-netstack','zero-copy'],['linux-netstack','ebpf'],
    ['db-replication','mysql-logs'],['db-replication','kafka-overview'],['db-replication','cap-theorem'],['db-replication','distributed-db'],
    ['db-explain','bplus'],['db-explain','db-query-plan'],['db-explain','db'],    ['db-conn-pool','db'],['db-conn-pool','go-sql'],['db-conn-pool','go-concurrency'],
    // Redis 补充
    ['redis-pipeline','redis-stream'],['redis-pipeline','tcp'],['redis-pubsub','redis-stream'],['redis-pubsub','kafka-overview'],
    // Distributed 补充
    ['dist-vector-clock','cap-theorem'],['dist-vector-clock','crdt'],['dist-service-discovery','raft'],['dist-service-discovery','gossip'],
    ['dist-service-discovery','consistent-hash'],['dist-tracing','obs-tracing'],['dist-tracing','http'],
    // System Design 补充
    ['sd-api-gateway','lb'],['sd-api-gateway','redis-types'],['sd-api-gateway','tls'],['sd-api-gateway','grpc'],
    ['sd-notification','kafka-overview'],['sd-notification','redis-types'],['sd-webcrawler','bloom'],['sd-webcrawler','bfs'],
    ['sd-video','network-cdn'],['sd-video','consistent-hash'],['sd-payment','dist-2pc'],['sd-payment','redis-lock'],
    ['sd-monitoring','obs-prometheus'],['sd-monitoring','kafka-consumer'],['sd-monitoring','redis-types'],
    // AI 补充
    ['ai-tokenization','ai-llm-overview'],['ai-llm-serving','ai-kv-cache'],['ai-llm-serving','memory-addressing'],
    ['ai-multimodal','ai-diffusion'],['ai-multimodal','ai-attention'],['ai-context-length','ai-kv-cache'],['ai-context-length','ai-attention'],
    // Network 补充
    ['network-cdn','dns'],['network-cdn','lb'],['network-nat','tcp'],['network-bgp','dns'],['network-bgp','lb'],
    // Linux 补充
    ['linux-container','cgroup'],['linux-container','ebpf'],['linux-container','cn-docker'],['linux-perf','ebpf'],
    ['linux-perf','linux-process'],['linux-systemd','cgroup'],['linux-systemd','linux-process'],
    // DB 补充
    ['db-sharding','consistent-hash'],['db-sharding','distributed-db'],['db-fulltext','bloom'],['db-fulltext','bplus'],
    // CS 补充
    ['cs-branch','cpu-pipeline'],['cs-tlb','memory-addressing'],['cs-numa','cache-hierarchy'],['cs-numa','memory-addressing'],
    // Algo 补充
    ['algo-maxflow','bfs'],['algo-maxflow','dijkstra'],['algo-strhash','kmp'],['algo-strhash','sliding-window'],
    ['algo-bitmanip','dp'],['algo-bitmanip','hash'],['algo-twoptr','sliding-window'],['algo-twoptr','bfs'],
    ['algo-dc','sort'],['algo-dc','dp'],
    // Cloud Native 内部
    ['cn-docker','linux-container'],['cn-docker','cgroup'],['cn-kubernetes','raft'],['cn-kubernetes','cn-docker'],
    ['cn-scheduling','cn-kubernetes'],['cn-networking','tcp'],['cn-networking','linux-container'],
    ['cn-hpa','sd-monitoring'],['cn-hpa','obs-prometheus'],
    ['cn-serverless','cn-docker'],['cn-serverless','cn-hpa'],['cn-serverless','kafka-consumer'],
    ['cn-gitops','cn-kubernetes'],['cn-gitops','cn-docker'],['cn-gitops','raft'],
    ['cn-service-mesh','cn-networking'],['cn-service-mesh','tls'],['cn-service-mesh','obs-tracing'],['cn-service-mesh','sec-pki'],
    ['cn-operator','cn-kubernetes'],['cn-operator','raft'],
    ['cn-storage','cn-kubernetes'],['cn-storage','distributed-db'],
    ['cn-helm','cn-kubernetes'],
    // Observability 内部
    ['obs-prometheus','sd-monitoring'],['obs-prometheus','kafka-consumer'],['obs-tracing','dist-tracing'],
    ['obs-tracing','http'],['obs-slo','obs-prometheus'],['obs-slo','sd-monitoring'],
    ['obs-logging','kafka-consumer'],['obs-logging','obs-otel'],
    ['obs-otel','obs-tracing'],['obs-otel','obs-prometheus'],['obs-otel','obs-logging'],
    ['obs-grafana','obs-prometheus'],['obs-grafana','obs-slo'],
    ['obs-chaos','obs-prometheus'],['obs-chaos','obs-slo'],
    // Security 内部
    ['sec-crypto','tls'],['sec-oauth','sec-jwt'],['sec-oauth','http'],['sec-jwt','http'],
    ['sec-web-attacks','db'],['sec-web-attacks','http'],['sec-jwt','redis-types'],
    ['sec-pki','tls'],['sec-pki','sec-crypto'],
    ['sec-secrets','sec-pki'],['sec-secrets','cn-kubernetes'],
    ['sec-container','cn-docker'],['sec-container','cn-kubernetes'],['sec-container','cgroup'],
    ['sec-supply-chain','cn-docker'],['sec-supply-chain','sec-pki'],
    ['sec-zero-trust','sec-pki'],['sec-zero-trust','tls'],['sec-zero-trust','cn-service-mesh'],
    // Algo 新增
    ['algo-prim','algo-kruskal'],['algo-prim','heap'],['algo-prim','union-find'],
    ['algo-edit-distance','algo-lcs'],['algo-edit-distance','dp'],
    ['algo-interval-dp','dp'],['algo-interval-dp','algo-edit-distance'],
    // DB 新增
    ['db-timeseries','lsm'],['db-timeseries','wal'],['db-timeseries','obs-prometheus'],
    ['db-column-store','storage-layout'],['db-column-store','db-timeseries'],
    ['db-graph-db','bfs'],['db-graph-db','dijkstra'],['db-graph-db','vector'],
    // Network 新增
    ['network-ip','tcp'],['network-ip','network-vxlan'],
    ['network-vxlan','cn-networking'],['network-vxlan','network-ip'],
    // Distributed 新增
    ['dist-lease','raft'],['dist-lease','zookeeper'],['dist-lease','redis-lock'],
    ['dist-quorum','raft'],['dist-quorum','consistent-hash'],['dist-quorum','dist-lease'],
    // AI 新增
    ['ai-guardrails','ai-llm-overview'],['ai-guardrails','ai-prompt-eng'],
    ['ai-structured-output','ai-llm-overview'],['ai-structured-output','ai-agent'],
    ['ai-inference-opt','ai-kv-cache'],['ai-inference-opt','ai-llm-serving'],['ai-inference-opt','ai-attention'],
    // Linux 新增
    ['linux-io-uring','epoll'],['linux-io-uring','zero-copy'],
    ['linux-dpdk','linux-io-uring'],['linux-dpdk','zero-copy'],['linux-dpdk','network-ip'],
    // System Design 新增
    ['sd-config-center','kafka-consumer'],['sd-config-center','redis-types'],
    ['sd-multi-region','raft'],['sd-multi-region','consistent-hash'],['sd-multi-region','distributed-db'],
    // Golang 新增
    ['go-cgo','go-runtime'],['go-cgo','go-unsafe'],
    ['go-build','go-modules'],['go-build','go-testing'],
    // AI 新增
    ['ai-spec-decode','ai-inference-opt'],['ai-spec-decode','ai-kv-cache'],['ai-spec-decode','ai-llm-serving'],
    ['ai-llm-reasoning','ai-prompt-eng'],['ai-llm-reasoning','ai-agent'],['ai-llm-reasoning','ai-llm-overview'],
    ['ai-model-merging','ai-fine-tuning'],['ai-model-merging','ai-llm-overview'],['ai-model-merging','ai-rlhf'],
    // Algo 新增
    ['algo-suffix-array','kmp'],['algo-suffix-array','algo-strhash'],['algo-suffix-array','trie'],
    ['algo-tarjan-scc','dfs'],['algo-tarjan-scc','union-find'],['algo-tarjan-scc','topo'],
    ['algo-bipartite','bfs'],['algo-bipartite','algo-maxflow'],['algo-bipartite','union-find'],
    ['algo-hld','segment-tree'],['algo-hld','algo-tree-traversal'],['algo-hld','dfs'],
    // System Design 新增
    ['sd-recommendation','db-vector'],['sd-recommendation','redis-types'],['sd-recommendation','kafka-consumer'],
    ['sd-live-streaming','network-cdn'],['sd-live-streaming','sd-video'],['sd-live-streaming','websocket'],
    ['sd-search-engine','db-fulltext'],['sd-search-engine','sd-webcrawler'],['sd-search-engine','kafka-consumer'],
    // Distributed 新增
    ['dist-3pc','dist-2pc'],['dist-3pc','raft'],['dist-3pc','paxos'],
    ['dist-spanner','paxos'],['dist-spanner','dist-2pc'],['dist-spanner','consistent-hash'],['dist-spanner','dist-3pc'],
    // Golang 新增页面
    ['go-perf-tuning','go-pprof'],['go-perf-tuning','go-escape'],['go-perf-tuning','go-syncpool'],['go-perf-tuning','go-runtime'],
    ['go-assembly','go-runtime'],['go-assembly','go-unsafe'],['go-assembly','go-mem-alloc'],
    // CS 新增
    ['cs-gpu-arch','cpu-pipeline'],['cs-gpu-arch','cache-hierarchy'],['cs-gpu-arch','cs-numa'],['cs-gpu-arch','ai-llm-serving'],
    // DB 新增
    ['db-nosql','distributed-db'],['db-nosql','db-sharding'],['db-nosql','db-graph-db'],
    // Testing 模块边
    ['testing','go-testing'],['testing','obs-chaos'],['testing','ai-eval-deploy'],
    ['test-pyramid','go-testing'],['test-pyramid','test-mock'],['test-pyramid','test-tdd'],
    ['test-mock','go-testing'],['test-mock','go-interface'],
    ['test-load','obs-prometheus'],['test-load','sd-rate-limiter'],['test-load','network-cdn'],
    ['test-contract','grpc'],['test-contract','test-pyramid'],
    ['test-fuzz','go-testing'],['test-fuzz','test-pyramid'],
    ['test-tdd','go-testing'],['test-tdd','go-error']
  ];
})();
